import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.about': 'About Paula',
    'nav.method': 'The Method',
    'nav.programs': 'Programs',
    'nav.retreat': 'Earth Rhythm Retreat',
    'nav.masterclass': 'Masterclass',
    'nav.resources': 'Resources',
    'nav.tools': 'Tools',
    'nav.shop': 'Shop',
    'nav.blog': 'Blog',
    'nav.faq': 'FAQ',
    'nav.contact': "Book a Consultation",
    'nav.values': 'Values',
    'nav.midlife': 'Midlife',
    'nav.foodRhythm': 'Food Rhythm Tool',
    'nav.rhythmCalc': 'Rhythm Calculator',
    
    // Home
    'home.hero.badge': 'Solaris Nutri Framework',
    'home.hero.title1': "Understand your biology.",
    'home.hero.title2': "Return to your natural rhythm.",
    'home.hero.subtitle': "A science-informed approach to nutrition and metabolic wellbeing for midlife women experiencing insulin resistance, energy changes, cravings, digestive discomfort, or frustration after conventional dieting.",
    'home.hero.cta': "Book Your Consultation",
    'home.hero.tagline': "Solaris Nutri helps midlife women understand their biology, work with their natural rhythms, and create sustainable changes that support metabolic wellbeing.",
    'home.why.title': "A different approach to metabolic wellbeing",
    'home.why.p1': "If you have tried counting calories, cutting out foods, and following conventional diets without lasting change, you are not alone. Midlife can bring changes in energy, appetite, sleep, digestion, body composition and metabolic health, and these are influenced by more than food alone: meal timing,",
    'home.why.highlight': 'circadian rhythms',
    'home.why.p1end': ", sleep, stress, movement, digestion and behavioural consistency all contribute to the bigger picture.",
    'home.why.p2': "At Solaris Nutri we do not treat your body as a problem to be controlled. We help you understand your individual biology and identify practical changes that support your health over time.",
    'home.phases.title': 'The Three Phases',
    'home.phases.decode.title': 'Decode',
    'home.phases.decode.desc': 'Understand your unique biological rhythm signature and identify misalignments causing fatigue, cravings, and inflammation.',
    'home.phases.reprogram.title': 'Reprogram',
    'home.phases.reprogram.desc': 'Reset your circadian clock through strategic meal timing, light exposure, and rhythm-aligned nutrition protocols.',
    'home.phases.rebuild.title': 'Rebuild',
    'home.phases.rebuild.desc': 'Establish sustainable rhythms that restore vitality, mental clarity, and emotional resilience for life.',
    'home.phases.cta': "Explore the Solaris Nutri Method",
    'home.cta.title': "Start with a consultation",
    'home.cta.subtitle': "The initial consultation is an opportunity to discuss your health history, current challenges, goals, daily routines and experience with conventional diets, and to see whether a three- or six-month programme is appropriate for you.",
    'home.cta.programs': 'Explore Programs',
    'home.cta.consult': "Book Your Consultation",
    // About
    'about.badge': 'About Paula',
    'about.title': "Meet Paula Suescun",
    'about.intro1': "is a science-informed nutrition and metabolic wellbeing practice founded by Paula Suescun, Nutritionist and Dietitian, Integrative Nutrition Health Coach, and creator of the Solaris Nutri",
    'about.intro2': 'method.',
    'about.story1': "Paula Suescun is a graduate Nutritionist and Dietitian from the National University of Colombia in Bogota, an Integrative Nutrition Health Coach trained at the Institute for Integrative Nutrition, and a former OsteoStrong certified instructor with additional training in longevity and biohacking. Through Solaris Nutri she works with midlife women experiencing insulin resistance, metabolic changes, low energy, cravings, digestive difficulties and frustration after years of conventional dieting.",
    'about.story2': "Her approach combines nutrition science, physiology, chronobiology, integrative health coaching, behaviour change and practical lifestyle strategies. Rather than focusing only on calories or restrictive food rules, Paula considers meal timing, sleep, morning light, stress, movement, digestion and appetite regulation. She believes the body is not a problem to be controlled, but a biological system to be understood, and her programmes give the time, structure and accountability needed to create meaningful change over three or six months.",
    'about.approach': 'My Approach',
    'about.approach1': 'Alignment over restriction — rhythm intelligence as foundation',
    'about.approach2': 'Integration of chronobiology, circadian science, and planetary rhythms',
    'about.approach3': 'Food as frequency and information, not just calories',
    'about.approach4': 'Compassionate guidance rooted in love, kindness, and respect for nature',
    'about.credentials': 'My Credentials',
    'about.cred1': "Nutritionist and Dietitian (National University of Colombia, Bogota)",
    'about.cred2': "Integrative Nutrition Health Coach (Institute for Integrative Nutrition)",
    'about.cred3': 'Basic and advanced levels of Pranic Healing',
    'about.cred4': "Founder of Solaris Nutri",
    'about.cred5': "Former OsteoStrong certified instructor; training in longevity and biohacking",
    'about.pillars': 'Core Pillars',
    'about.value.rhythm': 'Rhythm',
    'about.value.rhythm.desc': 'Honouring circadian, lunar, seasonal, and digestive cycles.',
    'about.value.nature': 'Nature & Natural Integrity',
    'about.value.nature.desc': 'Trusting natural simplicity as the ultimate teacher, and choosing minimally industrialised foods that sustain vitality and ecological balance.',
    'about.value.integration': 'Integration',
    'about.value.integration.desc': 'Merging modern science with ancestral, biodynamic, TCM spleen-focused, and esoteric knowledge.',
    'about.value.education': 'Nourishment',
    'about.value.education.desc': 'Real food as information — quality, diversity and timing that truly nourish.',
    'about.value.simplicity': 'Ecosystem',
    'about.value.simplicity.desc': 'Digestion, metabolism, microbiome, nervous system and immunity as one connected whole.',
    'about.value.evolution': 'Regulation',
    'about.value.evolution.desc': 'Metabolic regulation and sustainable habits instead of restriction and control.',
    'about.value.integrity': 'Natural Integrity',
    'about.value.integrity.desc': 'Choosing minimally industrialised foods that sustain vitality and ecological balance.',

    // Method
    'method.badge': 'The Method',
    'method.title': 'The Solaris Nutri Method',
    'method.headline': 'Decode your biology. Rebuild your foundations. Reprogram your patterns. Align with your natural rhythm.',
    'method.subtitle': 'The Solaris Nutri Method is a four-stage approach that helps you understand your biology, re-establish supportive foundations, create sustainable patterns, and bring your lifestyle into greater alignment with your natural rhythms.',
    'method.support': 'The Solaris Nutri Method is not a restrictive diet. It is a structured, science-informed process for understanding your body and creating sustainable change over time.',
    'method.decode': 'Decode',
    'method.decode.intro': 'Understand your individual biology, daily rhythms, symptoms, habits, and metabolic patterns. Identify the factors that may be influencing your energy, appetite, digestion, sleep, cravings, and insulin sensitivity.',
    'method.rebuild': 'Rebuild',
    'method.rebuild.intro': 'Re-establish the foundations that support metabolic wellbeing, including nourishing meals, consistent meal timing, sleep, movement, morning light, digestion, and nervous-system regulation.',
    'method.reprogram': 'Reprogram',
    'method.reprogram.intro': 'Introduce new, sustainable patterns that work with your physiology. Develop routines that support consistency and help you respond differently to old triggers and habits.',
    'method.align': 'Align',
    'method.align.intro': "Bring your nutrition, lifestyle, biological rhythms, and personal circumstances into greater alignment. Create a way of living that feels sustainable, realistic, and connected to your body's natural intelligence.",
    'method.science': 'Scientific Foundation',
    'method.science.desc': 'The Solaris Nutri Method is grounded in peer-reviewed research on circadian biology, chrononutrition, and metabolic health.',
    'method.cta.title': 'Ready to Begin Your Rhythm Reset?',
    'method.cta.desc': 'Choose from 3-week, 6-week, or 9-week programs — each designed to guide you through all three phases.',
    'method.cta.button': 'Explore Programs',

    // Resources
    'resources.badge': 'Resources & Learning',
    'resources.title': 'Rhythm Tools & Guides',
    'resources.subtitle': 'Free downloads and masterclasses to support your journey back to natural alignment.',
    'resources.rhythmCalc': 'Rhythm Calculator',
    'resources.rhythmCalc.desc': 'Interactive assessment to discover your optimal eating windows.',
    'resources.rhythmPlanner': 'Rhythm Planner',
    'resources.rhythmPlanner.desc': 'Track your daily rhythms, energy patterns, and alignment progress.',
    'resources.cerealChart': 'Cereal of the Week Chart',
    'resources.cerealChart.desc': "Steiner's planetary grain wisdom for weekly rhythm integration.",
    'resources.springGuide': 'Spring Seasonal Guide',
    'resources.springGuide.desc': "Nourishment protocols aligned with spring's awakening energy.",
    'resources.summerGuide': 'Summer Seasonal Guide',
    'resources.summerGuide.desc': "Peak vitality nourishment for summer's expansive rhythms.",
    'resources.autumnGuide': 'Autumn Seasonal Guide',
    'resources.autumnGuide.desc': 'Grounding nutrition as nature turns inward.',
    'resources.winterGuide': 'Winter Seasonal Guide',
    'resources.winterGuide.desc': "Deep nourishment protocols for winter's restorative phase.",
    'resources.newsletter.title': 'Join the Rhythm Field',
    'resources.newsletter.desc': 'Receive planetary rhythm insights, seasonal nourishment guides, and exclusive access to new resources delivered to your inbox.',
    'resources.newsletter.placeholder': 'Enter your email',
    'resources.newsletter.button': 'Subscribe',
    'resources.startAssessment': 'Start Assessment',
    'resources.downloadFree': 'Download Free',
    'resources.interactiveTool': 'Interactive Tool',
    'resources.pdfDownload': 'PDF Download',

    // Blog
    'blog.badge': 'Journal',
    'blog.title': 'Rhythmic Reflections',
    'blog.subtitle': 'Insights on rhythm, planetary cycles, and the path back to natural alignment.',
    'blog.readMore': 'Read Full Article',
    'blog.newsletter.title': 'Never Miss a Reflection',
    'blog.newsletter.desc': 'Subscribe to receive new articles and rhythmic insights in your inbox.',

    // Shop
    'shop.badge': 'Artisan Nourishment',
    'shop.title': 'Solaris Granola',
    'shop.subtitle': "Handcrafted, rhythm-aligned granola slow-roasted at 120°C to preserve life force and nourish your body's natural intelligence.",
    'shop.product': 'Solaris Morning Granola',
    'shop.product.desc': 'A carefully curated blend of organic oats, seeds, nuts, and natural sweeteners, slow-roasted at precisely 120°C to maintain nutritional integrity and support your morning rhythm activation.',
    'shop.product.details': '350g · Handmade in small batches · Organic ingredients',
    'shop.orderNow': 'Order Now',
    'shop.whyTitle': 'Why Slow-Roasting at 120°C Matters',
    'shop.whyDesc': 'Temperature is everything. Unlike commercial granolas roasted at 180°C+, our gentle process honours the living intelligence within each ingredient.',
    'shop.feature1.title': 'Slow-Roasted at 120°C',
    'shop.feature1.desc': 'Low-temperature roasting preserves delicate nutrients, enzymes, and the natural life force of ingredients that high heat destroys.',
    'shop.feature2.title': 'Enzyme Preservation',
    'shop.feature2.desc': 'Cooking below 120°C maintains beneficial enzymes that aid digestion and nutrient absorption, keeping your gut rhythm aligned.',
    'shop.feature3.title': 'Enhanced Bioavailability',
    'shop.feature3.desc': 'Gentle roasting unlocks nutrients while maintaining their bioactive form, allowing your body to fully absorb and utilize them.',
    'shop.feature4.title': 'Rhythmic Nourishment',
    'shop.feature4.desc': 'Crafted to support your circadian rhythm — perfect for morning activation without the inflammatory stress of processed cereals.',
    'shop.science': 'The Science of Gentle Heat',
    'shop.science.p1': 'Above 120°C, many heat-sensitive nutrients begin to degrade. Vitamin C, B vitamins, and beneficial enzymes are particularly vulnerable to high temperatures.',
    'shop.science.p2': 'The Maillard reaction that creates that satisfying golden crunch can occur gently at lower temperatures, preserving flavour while protecting nutritional value.',
    'shop.science.p3': 'Slow roasting allows for even heat distribution, ensuring every oat, seed, and nut reaches its optimal state without the oxidative damage caused by rapid high-heat cooking.',

    // Retreat
    'retreat.badge': 'One-Day Realignment Retreat',
    'retreat.title': 'Earth Rhythm Reset',
    'retreat.subtitle': 'A structured, physiology-centered reset designed for small groups in a serene mud house surrounded by olive trees and the natural silence of the Algarve.',
    'retreat.location': 'Algarve, Portugal',
    'retreat.book': 'Book Your Retreat Experience',
    'retreat.whyTitle': 'Why This Retreat Works',
    'retreat.whyIntro': 'Your biology is rhythmic, electric, and adaptive. When stress, poor sleep, and modern life disrupt those rhythms, everything becomes harder: energy drops, digestion slows, inflammation rises, cravings intensify, and mental clarity fades.',
    'retreat.whyResult': 'The Earth Rhythm Reset restores coherence through a sequence of proven physiological levers:',
    'retreat.result': 'The result: your system finds flow again.',
    'retreat.schedule': 'The Experience',
    'retreat.takeHome': 'What You Take Home',
    'retreat.pricing': 'Pricing',
    'retreat.faq': 'Frequently Asked Questions',

    // Programs
    'programs.title': 'Transform Your Rhythm',
    'programs.subtitle': 'Choose your path to alignment. All programs include personalized support in English, Spanish, and Portuguese.',
    'programs.available': 'Available in English, Spanish & Portuguese',
    'programs.3month': '3-Month Rhythm Reset',
    'programs.6month': '6-Month Coherence Deepening',
    'programs.9month': '9-Month Full Solaris Nutri Embodiment',
    'programs.book': 'Book Your Rhythm Consultation',
    'programs.popular': 'Most Popular',
    'programs.duration': 'Duration',
    'programs.investment': 'Investment',
    'programs.includes': 'What\'s Included',
    'programs.allInclude': 'All Programs Include',
    'programs.notSure': 'Not Sure Which Program?',
    'programs.notSure.desc': 'Book a free 20-minute discovery call to discuss your unique rhythm needs.',
    'programs.discovery': 'Schedule Discovery Call',
    
    // Contact
    'contact.badge': 'Contact',
    'contact.title': "Let's Begin Your Rhythm Journey",
    'contact.subtitle': 'Ready to begin your rhythm alignment journey? Consultations available in English, Spanish, and Portuguese.',
    'contact.languages': 'Consultations available in English, Spanish & Portuguese',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.interest': 'Interest',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.email.title': 'Email Directly',
    'contact.email.desc': 'For quick questions or inquiries',
    'contact.call.title': 'Book a Discovery Call',
    'contact.call.desc': 'Schedule a free 20-minute call to discuss your rhythm alignment needs',
    'contact.call.button': 'Schedule Call',
    'contact.expect': 'What to Expect',
    'contact.expect.1': 'Response within 24-48 hours',
    'contact.expect.2': 'Personalized guidance based on your needs',
    'contact.expect.3': 'No pressure, just information',
    'contact.quote': '"Every body has its own rhythm. My role is to help you rediscover yours."',
    
    // Calculator
    'calc.badge': 'Spleen Rhythm Assessment',
    'calc.title': 'Assess Your Digestive Rhythm',
    'calc.subtitle': 'Answer 10 questions to understand your spleen rhythm and receive personalized recommendations for the 3-Month Rhythm Reset Program.',
    'calc.instruction': 'Rate each statement 0–3:',
    'calc.never': 'Never',
    'calc.occasionally': 'Occasionally',
    'calc.frequently': 'Frequently',
    'calc.almostAlways': 'Almost Always',
    'calc.question': 'Question',
    'calc.of': 'of',
    'calc.select': 'Select the rating that best describes your experience',
    'calc.back': 'Back',
    'calc.next': 'Next',
    'calc.seeResults': 'See Results',
    'calc.results.title': 'Your Spleen Rhythm Assessment',
    'calc.results.score': 'Total Score',
    'calc.results.recommendations': 'Your Personalized Recommendations',
    'calc.results.nextSteps': 'Recommended Next Steps',
    'calc.results.retake': 'Retake Assessment',
    'calc.results.download': 'Download Your Results',
    'calc.results.ready': 'Ready to Restore Your Rhythm?',
    'calc.results.readyDesc': 'Discover how Solaris Nutri Framework can help you realign with your body\'s natural intelligence.',
    'calc.results.bookConsult': 'Book Consultation',
    'calc.results.exploreResources': 'Explore Resources',
    'calc.results.viewPrograms': 'View Programs',
    'calc.results.exploreRetreat': 'Explore Earth Rhythm Reset Retreat',
    
    // Footer
    'footer.tagline': 'Guiding alignment across the seen and unseen bodies',
    'footer.rights': 'All rights reserved.',
    'footer.explore': 'Explore',
    'footer.connect': 'Connect',
    'footer.book': 'Book a Session',
    'footer.email': 'Email Us',
    'footer.createdBy': 'Created by Paula Carolina Suescun — BioRhythm Nutrition Coach & Nutritionist',
    
    // Common
    'common.learnMore': 'Learn More',
    'common.bookNow': 'Book Now',
    'common.comingSoon': 'Coming Soon',
    'common.enroll': 'Enroll Now',
    'common.register': 'Register Now',
    'common.free': 'Free',

    // Masterclass Section
    'masterclass.badge': 'Masterclasses',
    'masterclass.title': 'Deep Dive Learning',
    'masterclass.subtitle': 'Comprehensive masterclasses to deepen your understanding of rhythm, nourishment, and the hidden patterns that shape your vitality.',
    'masterclass.live': 'Live Masterclass',
    'masterclass.online': 'ONLINE MASTERCLASS',
    'masterclass.bundle': 'Complete Masterclass Bundle',
    'masterclass.bundleDesc': 'Access all masterclasses and save 30% with the complete bundle.',
    'masterclass.getBundle': 'Get Bundle Access',
    'masterclass.notify': 'Notify When Available',
  },
  es: {
    // Navigation
    'nav.about': 'Sobre Paula',
    'nav.method': 'El Método',
    'nav.programs': 'Programas',
    'nav.retreat': 'Retiro Ritmo Tierra',
    'nav.masterclass': 'Masterclass',
    'nav.resources': 'Recursos',
    'nav.tools': 'Herramientas',
    'nav.shop': 'Tienda',
    'nav.blog': 'Blog',
    'nav.faq': 'Preguntas',
    'nav.contact': "Reservar Consulta",
    'nav.values': 'Valores',
    'nav.midlife': 'Mediana edad',
    'nav.foodRhythm': 'Herramienta de Ritmo',
    'nav.rhythmCalc': 'Calculadora de Ritmo',
    
    // Home
    'home.hero.badge': 'Marco de Ritmo Cuántico',
    'home.hero.title1': "Comprende tu biología.",
    'home.hero.title2': "Vuelve a tu ritmo natural.",
    'home.hero.subtitle': "Un enfoque basado en ciencia sobre nutrición y bienestar metabólico para mujeres en la mediana edad con resistencia a la insulina, cambios de energía, antojos, molestias digestivas o frustración tras dietas convencionales.",
    'home.hero.cta': "Reserva Tu Consulta",
    'home.hero.tagline': "Solaris Nutri ayuda a mujeres en la mediana edad a comprender su biología, trabajar con sus ritmos naturales y crear cambios sostenibles que apoyan el bienestar metabólico.",
    'home.why.title': "Un enfoque diferente del bienestar metabólico",
    'home.why.p1': "Si has contado calorías, eliminado alimentos y seguido dietas convencionales sin un cambio duradero, no estás sola. La mediana edad puede traer cambios en energía, apetito, sueño, digestión, composición corporal y salud metabólica, influidos por mucho más que la comida: los horarios de las comidas, los",
    'home.why.highlight': 'ritmos circadianos',
    'home.why.p1end': ", el sueño, el estrés, el movimiento, la digestión y la consistencia de los hábitos forman el cuadro completo.",
    'home.why.p2': "En Solaris Nutri no tratamos tu cuerpo como un problema que controlar. Te ayudamos a comprender tu biología individual y a identificar cambios prácticos que sostienen tu salud en el tiempo.",
    'home.phases.title': 'Las Tres Fases',
    'home.phases.decode.title': 'Decodificar',
    'home.phases.decode.desc': 'Comprende tu firma de ritmo biológico e identifica las desalineaciones que causan fatiga, antojos e inflamación.',
    'home.phases.reprogram.title': 'Reprogramar',
    'home.phases.reprogram.desc': 'Restablece tu reloj circadiano a través de horarios estratégicos de comidas, exposición a la luz y protocolos de nutrición alineados.',
    'home.phases.rebuild.title': 'Reconstruir',
    'home.phases.rebuild.desc': 'Establece ritmos sostenibles que restauran la vitalidad, claridad mental y resiliencia emocional para toda la vida.',
    'home.phases.cta': "Explora el Método Solaris Nutri",
    'home.cta.title': "Comienza con una consulta",
    'home.cta.subtitle': "La consulta inicial es una oportunidad para revisar tu historia de salud, tus retos actuales, tus objetivos, tus rutinas diarias y tu experiencia con dietas convencionales, y ver si un programa de tres o seis meses es adecuado para ti.",
    'home.cta.programs': 'Explorar Programas',
    'home.cta.consult': "Reserva Tu Consulta",
    // About
    'about.badge': 'Sobre Paula',
    'about.title': "Conoce a Paula Suescun",
    'about.intro1': "es una práctica de nutrición y bienestar metabólico basada en ciencia, fundada por Paula Suescun, Nutricionista y Dietista, Health Coach en Nutrición Integrativa y creadora del",
    'about.intro2': '.',
    'about.story1': "Paula Suescun es Nutricionista y Dietista graduada de la Universidad Nacional de Colombia en Bogotá, Health Coach en Nutrición Integrativa formada en el Institute for Integrative Nutrition y ex instructora certificada de OsteoStrong, con formación adicional en longevidad y biohacking. A través de Solaris Nutri acompaña a mujeres en la mediana edad con resistencia a la insulina, cambios metabólicos, poca energía, antojos, dificultades digestivas y frustración tras años de dietas convencionales.",
    'about.story2': "Su enfoque combina ciencia de la nutrición, fisiología, cronobiología, coaching integrativo de salud, cambio de comportamiento y estrategias prácticas de estilo de vida. En lugar de centrarse solo en calorías o reglas restrictivas, Paula considera los horarios de comida, el sueño, la luz matinal, el estrés, el movimiento, la digestión y la regulación del apetito. Cree que el cuerpo no es un problema que controlar, sino un sistema biológico que comprender, y sus programas ofrecen el tiempo, la estructura y el acompañamiento necesarios para crear un cambio significativo en tres o seis meses.",
    'about.approach': 'Mi Enfoque',
    'about.approach1': 'Alineación sobre restricción — inteligencia rítmica como fundamento',
    'about.approach2': 'Integración de cronobiología, ciencia circadiana y ritmos planetarios',
    'about.approach3': 'Alimento como frecuencia e información, no solo calorías',
    'about.approach4': 'Guía compasiva enraizada en amor, amabilidad y respeto por la naturaleza',
    'about.credentials': 'Mis Credenciales',
    'about.cred1': "Nutricionista y Dietista (Universidad Nacional de Colombia, Bogotá)",
    'about.cred2': "Health Coach en Nutrición Integrativa (Institute for Integrative Nutrition)",
    'about.cred3': 'Niveles básico y avanzado de Sanación Pránica',
    'about.cred4': "Fundadora de Solaris Nutri",
    'about.cred5': "Ex instructora certificada de OsteoStrong; formación en longevidad y biohacking",
    'about.pillars': 'Pilares Fundamentales',
    'about.value.rhythm': 'Ritmo',
    'about.value.rhythm.desc': 'Honrando los ciclos circadianos, lunares, estacionales y digestivos.',
    'about.value.nature': 'Naturaleza e Integridad Natural',
    'about.value.nature.desc': 'Confiando en la simplicidad natural como la maestra definitiva, y eligiendo alimentos mínimamente industrializados que sostienen la vitalidad y el equilibrio ecológico.',
    'about.value.integration': 'Integración',
    'about.value.integration.desc': 'Fusionando ciencia moderna con conocimiento ancestral, biodinámico, enfoque del bazo en MTC y esotérico.',
    'about.value.education': 'Nutrición',
    'about.value.education.desc': 'La comida real como información — calidad, diversidad y momento que realmente nutren.',
    'about.value.simplicity': 'Ecosistema',
    'about.value.simplicity.desc': 'Digestión, metabolismo, microbiota, sistema nervioso e inmunidad como un todo conectado.',
    'about.value.evolution': 'Regulación',
    'about.value.evolution.desc': 'Regulación metabólica y hábitos sostenibles en lugar de restricción y control.',
    'about.value.integrity': 'Integridad Natural',
    'about.value.integrity.desc': 'Eligiendo alimentos mínimamente industrializados que sostienen la vitalidad y el equilibrio ecológico.',

    // Method
    'method.badge': 'El Método',
    'method.title': 'El Método Solaris Nutri',
    'method.headline': 'Decodifica tu biología. Reconstruye tus bases. Reprograma tus patrones. Alinéate con tu ritmo natural.',
    'method.subtitle': 'El Método Solaris Nutri es un enfoque de cuatro etapas que te ayuda a entender tu biología, restablecer bases que te sostienen, crear patrones sostenibles y alinear tu estilo de vida con tus ritmos naturales.',
    'method.support': 'El Método Solaris Nutri no es una dieta restrictiva. Es un proceso estructurado y basado en ciencia para entender tu cuerpo y crear un cambio sostenible en el tiempo.',
    'method.decode': 'Decodificar',
    'method.decode.intro': 'Comprende tu biología individual, tus ritmos diarios, síntomas, hábitos y patrones metabólicos. Identificamos los factores que pueden estar influyendo en tu energía, apetito, digestión, sueño, antojos y sensibilidad a la insulina.',
    'method.rebuild': 'Reconstruir',
    'method.rebuild.intro': 'Restablece las bases que sostienen el bienestar metabólico: comidas nutritivas, horarios de comida consistentes, sueño, movimiento, luz matinal, digestión y regulación del sistema nervioso.',
    'method.reprogram': 'Reprogramar',
    'method.reprogram.intro': 'Introduce patrones nuevos y sostenibles que funcionen con tu fisiología. Desarrolla rutinas que sostengan la consistencia y te ayuden a responder de otra forma a viejos detonantes y hábitos.',
    'method.align': 'Alinear',
    'method.align.intro': 'Alinea tu nutrición, estilo de vida, ritmos biológicos y circunstancias personales. Crea una forma de vivir que se sienta sostenible, realista y conectada con la inteligencia natural de tu cuerpo.',
    'method.science': 'Fundamento Científico',
    'method.science.desc': 'El Método Solaris Nutri está fundamentado en investigación revisada por pares sobre biología circadiana, crononutrición y salud metabólica.',
    'method.cta.title': '¿Lista para Comenzar Tu Reset de Ritmo?',
    'method.cta.desc': 'Elige entre programas de 3, 6 o 9 semanas — cada uno diseñado para guiarte a través de las tres fases.',
    'method.cta.button': 'Explorar Programas',

    // Resources
    'resources.badge': 'Recursos & Aprendizaje',
    'resources.title': 'Herramientas y Guías de Ritmo',
    'resources.subtitle': 'Descargas gratuitas y masterclasses para apoyar tu viaje de regreso a la alineación natural.',
    'resources.rhythmCalc': 'Calculadora de Ritmo',
    'resources.rhythmCalc.desc': 'Evaluación interactiva para descubrir tus ventanas óptimas de alimentación.',
    'resources.rhythmPlanner': 'Planificador de Ritmo',
    'resources.rhythmPlanner.desc': 'Rastrea tus ritmos diarios, patrones de energía y progreso de alineación.',
    'resources.cerealChart': 'Gráfico de Cereal de la Semana',
    'resources.cerealChart.desc': 'La sabiduría de los granos planetarios de Steiner para la integración del ritmo semanal.',
    'resources.springGuide': 'Guía Estacional de Primavera',
    'resources.springGuide.desc': 'Protocolos de nutrición alineados con la energía de despertar de la primavera.',
    'resources.summerGuide': 'Guía Estacional de Verano',
    'resources.summerGuide.desc': 'Nutrición de máxima vitalidad para los ritmos expansivos del verano.',
    'resources.autumnGuide': 'Guía Estacional de Otoño',
    'resources.autumnGuide.desc': 'Nutrición de arraigo mientras la naturaleza se vuelve hacia adentro.',
    'resources.winterGuide': 'Guía Estacional de Invierno',
    'resources.winterGuide.desc': 'Protocolos de nutrición profunda para la fase restauradora del invierno.',
    'resources.newsletter.title': 'Únete al Campo Rítmico',
    'resources.newsletter.desc': 'Recibe perspectivas de ritmos planetarios, guías de nutrición estacional y acceso exclusivo a nuevos recursos en tu bandeja de entrada.',
    'resources.newsletter.placeholder': 'Ingresa tu email',
    'resources.newsletter.button': 'Suscribirse',
    'resources.startAssessment': 'Iniciar Evaluación',
    'resources.downloadFree': 'Descargar Gratis',
    'resources.interactiveTool': 'Herramienta Interactiva',
    'resources.pdfDownload': 'Descarga PDF',

    // Blog
    'blog.badge': 'Diario',
    'blog.title': 'Reflexiones Rítmicas',
    'blog.subtitle': 'Perspectivas sobre ritmo, ciclos planetarios y el camino de regreso a la alineación natural.',
    'blog.readMore': 'Leer Artículo Completo',
    'blog.newsletter.title': 'Nunca Te Pierdas una Reflexión',
    'blog.newsletter.desc': 'Suscríbete para recibir nuevos artículos y perspectivas rítmicas en tu bandeja de entrada.',

    // Shop
    'shop.badge': 'Nutrición Artesanal',
    'shop.title': 'Granola Solaris',
    'shop.subtitle': 'Granola artesanal alineada con el ritmo, tostada lentamente a 120°C para preservar la fuerza vital y nutrir la inteligencia natural de tu cuerpo.',
    'shop.product': 'Granola Matutina Solaris',
    'shop.product.desc': 'Una mezcla cuidadosamente curada de avena orgánica, semillas, nueces y endulzantes naturales, tostada lentamente a precisamente 120°C para mantener la integridad nutricional y apoyar la activación de tu ritmo matutino.',
    'shop.product.details': '350g · Hecha a mano en pequeños lotes · Ingredientes orgánicos',
    'shop.orderNow': 'Ordenar Ahora',
    'shop.whyTitle': 'Por Qué Importa el Tostado Lento a 120°C',
    'shop.whyDesc': 'La temperatura es todo. A diferencia de las granolas comerciales tostadas a 180°C+, nuestro proceso suave honra la inteligencia viviente dentro de cada ingrediente.',
    'shop.feature1.title': 'Tostado Lento a 120°C',
    'shop.feature1.desc': 'El tostado a baja temperatura preserva nutrientes delicados, enzimas y la fuerza vital natural de los ingredientes que el calor alto destruye.',
    'shop.feature2.title': 'Preservación de Enzimas',
    'shop.feature2.desc': 'Cocinar por debajo de 120°C mantiene enzimas beneficiosas que ayudan a la digestión y absorción de nutrientes, manteniendo tu ritmo intestinal alineado.',
    'shop.feature3.title': 'Biodisponibilidad Mejorada',
    'shop.feature3.desc': 'El tostado suave desbloquea nutrientes mientras mantiene su forma bioactiva, permitiendo que tu cuerpo los absorba y utilice completamente.',
    'shop.feature4.title': 'Nutrición Rítmica',
    'shop.feature4.desc': 'Elaborada para apoyar tu ritmo circadiano — perfecta para la activación matutina sin el estrés inflamatorio de los cereales procesados.',
    'shop.science': 'La Ciencia del Calor Suave',
    'shop.science.p1': 'Por encima de 120°C, muchos nutrientes sensibles al calor comienzan a degradarse. La vitamina C, vitaminas B y enzimas beneficiosas son particularmente vulnerables a altas temperaturas.',
    'shop.science.p2': 'La reacción de Maillard que crea ese crujido dorado satisfactorio puede ocurrir suavemente a temperaturas más bajas, preservando el sabor mientras protege el valor nutricional.',
    'shop.science.p3': 'El tostado lento permite una distribución uniforme del calor, asegurando que cada avena, semilla y nuez alcance su estado óptimo sin el daño oxidativo causado por la cocción rápida a alto calor.',

    // Retreat
    'retreat.badge': 'Retiro de Realineación de Un Día',
    'retreat.title': 'Reset del Ritmo de la Tierra',
    'retreat.subtitle': 'Un reset estructurado centrado en la fisiología diseñado para grupos pequeños en una casa de barro serena rodeada de olivos y el silencio natural del Algarve.',
    'retreat.location': 'Algarve, Portugal',
    'retreat.book': 'Reserva Tu Experiencia de Retiro',
    'retreat.whyTitle': 'Por Qué Funciona Este Retiro',
    'retreat.whyIntro': 'Tu biología es rítmica, eléctrica y adaptativa. Cuando el estrés, el mal sueño y la vida moderna interrumpen esos ritmos, todo se vuelve más difícil: la energía baja, la digestión se ralentiza, la inflamación aumenta, los antojos se intensifican y la claridad mental se desvanece.',
    'retreat.whyResult': 'El Reset del Ritmo de la Tierra restaura la coherencia a través de una secuencia de palancas fisiológicas probadas:',
    'retreat.result': 'El resultado: tu sistema encuentra el flujo de nuevo.',
    'retreat.schedule': 'La Experiencia',
    'retreat.takeHome': 'Lo Que Te Llevas a Casa',
    'retreat.pricing': 'Precios',
    'retreat.faq': 'Preguntas Frecuentes',

    // Programs
    'programs.title': 'Transforma Tu Ritmo',
    'programs.subtitle': 'Elige tu camino hacia la alineación. Todos los programas incluyen apoyo personalizado en inglés, español y portugués.',
    'programs.available': 'Disponible en Inglés, Español y Portugués',
    'programs.3month': 'Reset de Ritmo de 3 Meses',
    'programs.6month': 'Profundización de Coherencia de 6 Meses',
    'programs.9month': 'Encarnación Completa de Ritmo Cuántico de 9 Meses',
    'programs.book': 'Reserva Tu Consulta de Ritmo',
    'programs.popular': 'Más Popular',
    'programs.duration': 'Duración',
    'programs.investment': 'Inversión',
    'programs.includes': 'Qué Incluye',
    'programs.allInclude': 'Todos los Programas Incluyen',
    'programs.notSure': '¿No Estás Segura de Cuál Programa?',
    'programs.notSure.desc': 'Reserva una llamada de descubrimiento gratuita de 20 minutos para discutir tus necesidades de ritmo únicas.',
    'programs.discovery': 'Agendar Llamada de Descubrimiento',
    
    // Contact
    'contact.badge': 'Contacto',
    'contact.title': 'Comencemos Tu Viaje Rítmico',
    'contact.subtitle': '¿Lista para comenzar tu viaje de alineación rítmica? Consultas disponibles en inglés, español y portugués.',
    'contact.languages': 'Consultas disponibles en Inglés, Español y Portugués',
    'contact.form.name': 'Nombre',
    'contact.form.email': 'Email',
    'contact.form.interest': 'Interés',
    'contact.form.message': 'Mensaje',
    'contact.form.send': 'Enviar Mensaje',
    'contact.email.title': 'Email Directo',
    'contact.email.desc': 'Para preguntas rápidas o consultas',
    'contact.call.title': 'Reservar Llamada de Descubrimiento',
    'contact.call.desc': 'Agenda una llamada gratuita de 20 minutos para discutir tus necesidades de alineación rítmica',
    'contact.call.button': 'Agendar Llamada',
    'contact.expect': 'Qué Esperar',
    'contact.expect.1': 'Respuesta en 24-48 horas',
    'contact.expect.2': 'Guía personalizada según tus necesidades',
    'contact.expect.3': 'Sin presión, solo información',
    'contact.quote': '"Cada cuerpo tiene su propio ritmo. Mi rol es ayudarte a redescubrir el tuyo."',
    
    // Calculator
    'calc.badge': 'Evaluación del Ritmo del Bazo',
    'calc.title': 'Evalúa Tu Ritmo Digestivo',
    'calc.subtitle': 'Responde 10 preguntas para comprender tu ritmo del bazo y recibe recomendaciones personalizadas para el Programa de Reset de Ritmo de 3 Meses.',
    'calc.instruction': 'Califica cada afirmación de 0 a 3:',
    'calc.never': 'Nunca',
    'calc.occasionally': 'Ocasionalmente',
    'calc.frequently': 'Frecuentemente',
    'calc.almostAlways': 'Casi Siempre',
    'calc.question': 'Pregunta',
    'calc.of': 'de',
    'calc.select': 'Selecciona la calificación que mejor describe tu experiencia',
    'calc.back': 'Atrás',
    'calc.next': 'Siguiente',
    'calc.seeResults': 'Ver Resultados',
    'calc.results.title': 'Tu Evaluación del Ritmo del Bazo',
    'calc.results.score': 'Puntuación Total',
    'calc.results.recommendations': 'Tus Recomendaciones Personalizadas',
    'calc.results.nextSteps': 'Próximos Pasos Recomendados',
    'calc.results.retake': 'Volver a Hacer la Evaluación',
    'calc.results.download': 'Descarga Tus Resultados',
    'calc.results.ready': '¿Lista para Restaurar Tu Ritmo?',
    'calc.results.readyDesc': 'Descubre cómo Solaris Nutri Framework puede ayudarte a realinearte con la inteligencia natural de tu cuerpo.',
    'calc.results.bookConsult': 'Reservar Consulta',
    'calc.results.exploreResources': 'Explorar Recursos',
    'calc.results.viewPrograms': 'Ver Programas',
    'calc.results.exploreRetreat': 'Explorar Retiro Earth Rhythm Reset',
    
    // Footer
    'footer.tagline': 'Guiando la alineación a través de los cuerpos vistos e invisibles',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.explore': 'Explorar',
    'footer.connect': 'Conectar',
    'footer.book': 'Reservar Sesión',
    'footer.email': 'Envíanos un Email',
    'footer.createdBy': 'Creado por Paula Carolina Suescun — Coach de Nutrición BioRítmica y Nutricionista',
    
    // Common
    'common.learnMore': 'Saber Más',
    'common.bookNow': 'Reservar Ahora',
    'common.comingSoon': 'Próximamente',
    'common.enroll': 'Inscríbete Ahora',
    'common.register': 'Regístrate Ahora',
    'common.free': 'Gratis',

    // Masterclass Section
    'masterclass.badge': 'Masterclasses',
    'masterclass.title': 'Aprendizaje Profundo',
    'masterclass.subtitle': 'Masterclasses completas para profundizar tu comprensión del ritmo, la nutrición y los patrones ocultos que dan forma a tu vitalidad.',
    'masterclass.live': 'Masterclass en Vivo',
    'masterclass.online': 'MASTERCLASS ONLINE',
    'masterclass.bundle': 'Paquete Completo de Masterclasses',
    'masterclass.bundleDesc': 'Accede a todas las masterclasses y ahorra 30% con el paquete completo.',
    'masterclass.getBundle': 'Obtener Acceso al Paquete',
    'masterclass.notify': 'Notificar Cuando Esté Disponible',
  },
  pt: {
    // Navigation
    'nav.about': 'Sobre Paula',
    'nav.method': 'O Método',
    'nav.programs': 'Programas',
    'nav.retreat': 'Retiro Ritmo da Terra',
    'nav.resources': 'Recursos & Masterclass',
    'nav.tools': 'Ferramentas',
    'nav.shop': 'Loja',
    'nav.blog': 'Blog',
    'nav.faq': 'Perguntas',
    'nav.contact': "Marcar Consulta",
    'nav.values': 'Valores',
    'nav.midlife': 'Meia-idade',
    'nav.foodRhythm': 'Ferramenta de Ritmo',
    'nav.rhythmCalc': 'Calculadora de Ritmo',
    
    // Home
    'home.hero.badge': 'Framework de Ritmo Quântico',
    'home.hero.title1': "Compreenda a sua biologia.",
    'home.hero.title2': "Regresse ao seu ritmo natural.",
    'home.hero.subtitle': "Uma abordagem informada pela ciência sobre nutrição e bem-estar metabólico para mulheres na meia-idade com resistência à insulina, alterações de energia, desejos alimentares, desconforto digestivo ou frustração após dietas convencionais.",
    'home.hero.cta': "Marque a Sua Consulta",
    'home.hero.tagline': "A Solaris Nutri ajuda mulheres na meia-idade a compreender a sua biologia, trabalhar com os seus ritmos naturais e criar mudanças sustentáveis que apoiam o bem-estar metabólico.",
    'home.why.title': "Uma abordagem diferente do bem-estar metabólico",
    'home.why.p1': "Se já contou calorias, cortou alimentos e seguiu dietas convencionais sem mudança duradoura, não está sozinha. A meia-idade pode trazer alterações na energia, apetite, sono, digestão, composição corporal e saúde metabólica, influenciadas por muito mais do que a comida: os horários das refeições, os",
    'home.why.highlight': 'ritmos circadianos',
    'home.why.p1end': ", o sono, o stress, o movimento, a digestão e a consistência dos hábitos formam o quadro completo.",
    'home.why.p2': "Na Solaris Nutri não tratamos o seu corpo como um problema a controlar. Ajudamos a compreender a sua biologia individual e a identificar mudanças práticas que apoiam a sua saúde ao longo do tempo.",
    'home.phases.title': 'As Três Fases',
    'home.phases.decode.title': 'Decodificar',
    'home.phases.decode.desc': 'Entenda sua assinatura de ritmo biológico única e identifique os desalinhamentos que causam fadiga, desejos e inflamação.',
    'home.phases.reprogram.title': 'Reprogramar',
    'home.phases.reprogram.desc': 'Redefina seu relógio circadiano através de horários estratégicos de refeições, exposição à luz e protocolos de nutrição alinhados.',
    'home.phases.rebuild.title': 'Reconstruir',
    'home.phases.rebuild.desc': 'Estabeleça ritmos sustentáveis que restauram vitalidade, clareza mental e resiliência emocional para a vida.',
    'home.phases.cta': "Explore o Método Solaris Nutri",
    'home.cta.title': "Comece com uma consulta",
    'home.cta.subtitle': "A consulta inicial é uma oportunidade para rever o seu historial de saúde, desafios atuais, objetivos, rotinas diárias e experiência com dietas convencionais, e perceber se um programa de três ou seis meses é adequado para si.",
    'home.cta.programs': 'Explorar Programas',
    'home.cta.consult': "Marque a Sua Consulta",
    // About
    'about.badge': 'Sobre Paula',
    'about.title': "Conheça Paula Suescun",
    'about.intro1': "é uma prática de nutrição e bem-estar metabólico informada pela ciência, fundada por Paula Suescun, Nutricionista e Dietista, Health Coach em Nutrição Integrativa e criadora do",
    'about.intro2': '.',
    'about.story1': "Paula Suescun é Nutricionista e Dietista formada pela Universidade Nacional da Colômbia em Bogotá, Health Coach em Nutrição Integrativa pelo Institute for Integrative Nutrition e antiga instrutora certificada OsteoStrong, com formação adicional em longevidade e biohacking. Através da Solaris Nutri acompanha mulheres na meia-idade com resistência à insulina, alterações metabólicas, pouca energia, desejos alimentares, dificuldades digestivas e frustração após anos de dietas convencionais.",
    'about.story2': "A sua abordagem combina ciência da nutrição, fisiologia, cronobiologia, coaching integrativo de saúde, mudança de comportamento e estratégias práticas de estilo de vida. Em vez de se centrar apenas em calorias ou regras restritivas, Paula considera os horários das refeições, o sono, a luz da manhã, o stress, o movimento, a digestão e a regulação do apetite. Acredita que o corpo não é um problema a controlar, mas um sistema biológico a compreender, e os seus programas dão o tempo, a estrutura e o acompanhamento necessários para criar mudança significativa em três ou seis meses.",
    'about.approach': 'Minha Abordagem',
    'about.approach1': 'Alinhamento sobre restrição — inteligência rítmica como fundamento',
    'about.approach2': 'Integração de cronobiologia, biologia quântica e ritmos planetários',
    'about.approach3': 'Alimento como frequência e informação, não apenas calorias',
    'about.approach4': 'Orientação compassiva enraizada em amor, bondade e respeito pela natureza',
    'about.credentials': 'Minhas Credenciais',
    'about.cred1': "Nutricionista e Dietista (Universidade Nacional da Colômbia, Bogotá)",
    'about.cred2': "Health Coach em Nutrição Integrativa (Institute for Integrative Nutrition)",
    'about.cred3': 'Níveis básico e avançado de Cura Prânica',
    'about.cred4': "Fundadora da Solaris Nutri",
    'about.cred5': "Antiga instrutora certificada OsteoStrong; formação em longevidade e biohacking",
    'about.pillars': 'Pilares Fundamentais',
    'about.value.rhythm': 'Ritmo',
    'about.value.rhythm.desc': 'Honrando os ciclos circadianos, lunares, sazonais e digestivos.',
    'about.value.nature': 'Natureza e Integridade Natural',
    'about.value.nature.desc': 'Confiando na simplicidade natural como a mestra definitiva, e escolhendo alimentos minimamente industrializados que sustentam vitalidade e equilíbrio ecológico.',
    'about.value.integration': 'Integração',
    'about.value.integration.desc': 'Fundindo ciência moderna com conhecimento ancestral, biodinâmico, foco no baço da MTC e esotérico.',
    'about.value.education': 'Nutrição',
    'about.value.education.desc': 'Comida real como informação — qualidade, diversidade e timing que realmente nutrem.',
    'about.value.simplicity': 'Ecossistema',
    'about.value.simplicity.desc': 'Digestão, metabolismo, microbiota, sistema nervoso e imunidade como um todo conectado.',
    'about.value.evolution': 'Regulação',
    'about.value.evolution.desc': 'Regulação metabólica e hábitos sustentáveis em vez de restrição e controlo.',
    'about.value.integrity': 'Integridade Natural',
    'about.value.integrity.desc': 'Escolhendo alimentos minimamente industrializados que sustentam vitalidade e equilíbrio ecológico.',

    // Method
    'method.badge': 'O Método',
    'method.title': 'O Método Solaris Nutri',
    'method.headline': 'Descodifique a sua biologia. Reconstrua as suas bases. Reprograme os seus padrões. Alinhe-se com o seu ritmo natural.',
    'method.subtitle': 'O Método Solaris Nutri é uma abordagem em quatro etapas que ajuda a compreender a sua biologia, restabelecer bases de apoio, criar padrões sustentáveis e alinhar o seu estilo de vida com os seus ritmos naturais.',
    'method.support': 'O Método Solaris Nutri não é uma dieta restritiva. É um processo estruturado e informado pela ciência para compreender o seu corpo e criar mudança sustentável ao longo do tempo.',
    'method.decode': 'Descodificar',
    'method.decode.intro': 'Compreenda a sua biologia individual, ritmos diários, sintomas, hábitos e padrões metabólicos. Identificamos os fatores que podem estar a influenciar a sua energia, apetite, digestão, sono, desejos alimentares e sensibilidade à insulina.',
    'method.rebuild': 'Reconstruir',
    'method.rebuild.intro': 'Restabeleça as bases que apoiam o bem-estar metabólico: refeições nutritivas, horários de refeição consistentes, sono, movimento, luz da manhã, digestão e regulação do sistema nervoso.',
    'method.reprogram': 'Reprogramar',
    'method.reprogram.intro': 'Introduza padrões novos e sustentáveis que funcionem com a sua fisiologia. Desenvolva rotinas que sustentem a consistência e ajudem a responder de forma diferente a velhos gatilhos e hábitos.',
    'method.align': 'Alinhar',
    'method.align.intro': 'Alinhe a sua nutrição, estilo de vida, ritmos biológicos e circunstâncias pessoais. Crie uma forma de viver que seja sustentável, realista e ligada à inteligência natural do seu corpo.',
    'method.science': 'Fundamento Científico',
    'method.science.desc': 'O Método Solaris Nutri está fundamentado em investigação revista por pares sobre biologia circadiana, cronutrição e saúde metabólica.',
    'method.cta.title': 'Pronta para Começar Seu Reset de Ritmo?',
    'method.cta.desc': 'Escolha entre programas de 3, 6 ou 9 semanas — cada um projetado para guiá-la através das três fases.',
    'method.cta.button': 'Explorar Programas',

    // Resources
    'resources.badge': 'Recursos & Aprendizado',
    'resources.title': 'Ferramentas e Guias de Ritmo',
    'resources.subtitle': 'Downloads gratuitos e masterclasses para apoiar sua jornada de volta ao alinhamento natural.',
    'resources.rhythmCalc': 'Calculadora de Ritmo',
    'resources.rhythmCalc.desc': 'Avaliação interativa para descobrir suas janelas ótimas de alimentação.',
    'resources.rhythmPlanner': 'Planejador de Ritmo',
    'resources.rhythmPlanner.desc': 'Acompanhe seus ritmos diários, padrões de energia e progresso de alinhamento.',
    'resources.cerealChart': 'Gráfico de Cereal da Semana',
    'resources.cerealChart.desc': 'A sabedoria dos grãos planetários de Steiner para integração do ritmo semanal.',
    'resources.springGuide': 'Guia Sazonal de Primavera',
    'resources.springGuide.desc': 'Protocolos de nutrição alinhados com a energia de despertar da primavera.',
    'resources.summerGuide': 'Guia Sazonal de Verão',
    'resources.summerGuide.desc': 'Nutrição de máxima vitalidade para os ritmos expansivos do verão.',
    'resources.autumnGuide': 'Guia Sazonal de Outono',
    'resources.autumnGuide.desc': 'Nutrição de enraizamento enquanto a natureza se volta para dentro.',
    'resources.winterGuide': 'Guia Sazonal de Inverno',
    'resources.winterGuide.desc': 'Protocolos de nutrição profunda para a fase restauradora do inverno.',
    'resources.newsletter.title': 'Junte-se ao Campo Rítmico',
    'resources.newsletter.desc': 'Receba insights de ritmos planetários, guias de nutrição sazonal e acesso exclusivo a novos recursos na sua caixa de entrada.',
    'resources.newsletter.placeholder': 'Digite seu email',
    'resources.newsletter.button': 'Inscrever-se',
    'resources.startAssessment': 'Iniciar Avaliação',
    'resources.downloadFree': 'Baixar Grátis',
    'resources.interactiveTool': 'Ferramenta Interativa',
    'resources.pdfDownload': 'Download PDF',

    // Blog
    'blog.badge': 'Diário',
    'blog.title': 'Reflexões Rítmicas',
    'blog.subtitle': 'Insights sobre ritmo, ciclos planetários e o caminho de volta ao alinhamento natural.',
    'blog.readMore': 'Ler Artigo Completo',
    'blog.newsletter.title': 'Nunca Perca uma Reflexão',
    'blog.newsletter.desc': 'Inscreva-se para receber novos artigos e insights rítmicos na sua caixa de entrada.',

    // Shop
    'shop.badge': 'Nutrição Artesanal',
    'shop.title': 'Granola Solaris',
    'shop.subtitle': 'Granola artesanal alinhada com o ritmo, torrada lentamente a 120°C para preservar a força vital e nutrir a inteligência natural do seu corpo.',
    'shop.product': 'Granola Matinal Solaris',
    'shop.product.desc': 'Uma mistura cuidadosamente curada de aveia orgânica, sementes, nozes e adoçantes naturais, torrada lentamente a precisamente 120°C para manter a integridade nutricional e apoiar a ativação do seu ritmo matinal.',
    'shop.product.details': '350g · Feita à mão em pequenos lotes · Ingredientes orgânicos',
    'shop.orderNow': 'Encomendar Agora',
    'shop.whyTitle': 'Por Que a Torra Lenta a 120°C Importa',
    'shop.whyDesc': 'A temperatura é tudo. Ao contrário das granolas comerciais torradas a 180°C+, nosso processo suave honra a inteligência viva dentro de cada ingrediente.',
    'shop.feature1.title': 'Torrada Lentamente a 120°C',
    'shop.feature1.desc': 'A torra em baixa temperatura preserva nutrientes delicados, enzimas e a força vital natural dos ingredientes que o calor alto destrói.',
    'shop.feature2.title': 'Preservação de Enzimas',
    'shop.feature2.desc': 'Cozinhar abaixo de 120°C mantém enzimas benéficas que auxiliam a digestão e absorção de nutrientes, mantendo seu ritmo intestinal alinhado.',
    'shop.feature3.title': 'Biodisponibilidade Melhorada',
    'shop.feature3.desc': 'A torra suave desbloqueia nutrientes enquanto mantém sua forma bioativa, permitindo que seu corpo os absorva e utilize completamente.',
    'shop.feature4.title': 'Nutrição Rítmica',
    'shop.feature4.desc': 'Elaborada para apoiar seu ritmo circadiano — perfeita para ativação matinal sem o estresse inflamatório dos cereais processados.',
    'shop.science': 'A Ciência do Calor Suave',
    'shop.science.p1': 'Acima de 120°C, muitos nutrientes sensíveis ao calor começam a degradar. A vitamina C, vitaminas B e enzimas benéficas são particularmente vulneráveis a altas temperaturas.',
    'shop.science.p2': 'A reação de Maillard que cria aquela crocância dourada satisfatória pode ocorrer suavemente em temperaturas mais baixas, preservando o sabor enquanto protege o valor nutricional.',
    'shop.science.p3': 'A torra lenta permite uma distribuição uniforme do calor, garantindo que cada aveia, semente e noz alcance seu estado ótimo sem o dano oxidativo causado pela cocção rápida em alto calor.',

    // Retreat
    'retreat.badge': 'Retiro de Realinhamento de Um Dia',
    'retreat.title': 'Reset do Ritmo da Terra',
    'retreat.subtitle': 'Um reset estruturado centrado na fisiologia projetado para pequenos grupos em uma casa de barro serena cercada por oliveiras e o silêncio natural do Algarve.',
    'retreat.location': 'Algarve, Portugal',
    'retreat.book': 'Reserve Sua Experiência de Retiro',
    'retreat.whyTitle': 'Por Que Este Retiro Funciona',
    'retreat.whyIntro': 'Sua biologia é rítmica, elétrica e adaptativa. Quando o estresse, o sono ruim e a vida moderna perturbam esses ritmos, tudo se torna mais difícil: a energia cai, a digestão desacelera, a inflamação aumenta, os desejos se intensificam e a clareza mental desvanece.',
    'retreat.whyResult': 'O Reset do Ritmo da Terra restaura a coerência através de uma sequência de alavancas fisiológicas comprovadas:',
    'retreat.result': 'O resultado: seu sistema encontra o fluxo novamente.',
    'retreat.schedule': 'A Experiência',
    'retreat.takeHome': 'O Que Você Leva para Casa',
    'retreat.pricing': 'Preços',
    'retreat.faq': 'Perguntas Frequentes',

    // Programs
    'programs.title': 'Transforme Seu Ritmo',
    'programs.subtitle': 'Escolha seu caminho para o alinhamento. Todos os programas incluem suporte personalizado em inglês, espanhol e português.',
    'programs.available': 'Disponível em Inglês, Espanhol e Português',
    'programs.3month': 'Reset de Ritmo de 3 Meses',
    'programs.6month': 'Aprofundamento de Coerência de 6 Meses',
    'programs.9month': 'Incorporação Completa de Ritmo Quântico de 9 Meses',
    'programs.book': 'Reserve Sua Consulta de Ritmo',
    'programs.popular': 'Mais Popular',
    'programs.duration': 'Duração',
    'programs.investment': 'Investimento',
    'programs.includes': 'O Que Inclui',
    'programs.allInclude': 'Todos os Programas Incluem',
    'programs.notSure': 'Não Tem Certeza de Qual Programa?',
    'programs.notSure.desc': 'Agende uma chamada de descoberta gratuita de 20 minutos para discutir suas necessidades de ritmo únicas.',
    'programs.discovery': 'Agendar Chamada de Descoberta',
    
    // Contact
    'contact.badge': 'Contacto',
    'contact.title': 'Vamos Começar Sua Jornada Rítmica',
    'contact.subtitle': 'Pronta para começar sua jornada de alinhamento rítmico? Consultas disponíveis em inglês, espanhol e português.',
    'contact.languages': 'Consultas disponíveis em Inglês, Espanhol e Português',
    'contact.form.name': 'Nome',
    'contact.form.email': 'Email',
    'contact.form.interest': 'Interesse',
    'contact.form.message': 'Mensagem',
    'contact.form.send': 'Enviar Mensagem',
    'contact.email.title': 'Email Direto',
    'contact.email.desc': 'Para perguntas rápidas ou consultas',
    'contact.call.title': 'Agendar Chamada de Descoberta',
    'contact.call.desc': 'Agende uma chamada gratuita de 20 minutos para discutir suas necessidades de alinhamento rítmico',
    'contact.call.button': 'Agendar Chamada',
    'contact.expect': 'O Que Esperar',
    'contact.expect.1': 'Resposta em 24-48 horas',
    'contact.expect.2': 'Orientação personalizada com base nas suas necessidades',
    'contact.expect.3': 'Sem pressão, apenas informação',
    'contact.quote': '"Cada corpo tem seu próprio ritmo. Meu papel é ajudá-la a redescobrir o seu."',
    
    // Calculator
    'calc.badge': 'Avaliação do Ritmo do Baço',
    'calc.title': 'Avalie Seu Ritmo Digestivo',
    'calc.subtitle': 'Responda 10 perguntas para entender seu ritmo do baço e receba recomendações personalizadas para o Programa de Reset de Ritmo de 3 Meses.',
    'calc.instruction': 'Classifique cada afirmação de 0 a 3:',
    'calc.never': 'Nunca',
    'calc.occasionally': 'Ocasionalmente',
    'calc.frequently': 'Frequentemente',
    'calc.almostAlways': 'Quase Sempre',
    'calc.question': 'Pergunta',
    'calc.of': 'de',
    'calc.select': 'Selecione a classificação que melhor descreve sua experiência',
    'calc.back': 'Voltar',
    'calc.next': 'Próximo',
    'calc.seeResults': 'Ver Resultados',
    'calc.results.title': 'Sua Avaliação do Ritmo do Baço',
    'calc.results.score': 'Pontuação Total',
    'calc.results.recommendations': 'Suas Recomendações Personalizadas',
    'calc.results.nextSteps': 'Próximos Passos Recomendados',
    'calc.results.retake': 'Refazer Avaliação',
    'calc.results.download': 'Baixe Seus Resultados',
    'calc.results.ready': 'Pronta para Restaurar Seu Ritmo?',
    'calc.results.readyDesc': 'Descubra como Solaris Nutri Framework pode ajudá-la a realinhar-se com a inteligência natural do seu corpo.',
    'calc.results.bookConsult': 'Agendar Consulta',
    'calc.results.exploreResources': 'Explorar Recursos',
    'calc.results.viewPrograms': 'Ver Programas',
    'calc.results.exploreRetreat': 'Explorar Retiro Earth Rhythm Reset',
    
    // Footer
    'footer.tagline': 'Guiando o alinhamento através dos corpos vistos e invistos',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.explore': 'Explorar',
    'footer.connect': 'Conectar',
    'footer.book': 'Agendar Sessão',
    'footer.email': 'Envie um Email',
    'footer.createdBy': 'Criado por Paula Carolina Suescun — Coach de Nutrição BioRítmica e Nutricionista',
    
    // Common
    'common.learnMore': 'Saiba Mais',
    'common.bookNow': 'Reserve Agora',
    'common.comingSoon': 'Em Breve',
    'common.enroll': 'Inscreva-se Agora',
    'common.register': 'Registre-se Agora',
    'common.free': 'Grátis',

    // Masterclass Section
    'masterclass.badge': 'Masterclasses',
    'masterclass.title': 'Aprendizado Profundo',
    'masterclass.subtitle': 'Masterclasses completas para aprofundar sua compreensão do ritmo, nutrição e os padrões ocultos que moldam sua vitalidade.',
    'masterclass.live': 'Masterclass ao Vivo',
    'masterclass.online': 'MASTERCLASS ONLINE',
    'masterclass.bundle': 'Pacote Completo de Masterclasses',
    'masterclass.bundleDesc': 'Acesse todas as masterclasses e economize 30% com o pacote completo.',
    'masterclass.getBundle': 'Obter Acesso ao Pacote',
    'masterclass.notify': 'Notificar Quando Disponível',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
