import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.about': 'About Paula',
    'nav.method': 'The Method',
    'nav.programs': 'Programs',
    'nav.retreat': 'Earth Rhythm Retreat',
    'nav.masterclass': 'Masterclass',
    'nav.resources': 'Resources',
    'nav.tools': 'Tools',
    'nav.shop': 'Shop',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'nav.foodRhythm': 'Food Rhythm Tool',
    'nav.rhythmCalc': 'Rhythm Calculator',
    
    // Home
    'home.hero.badge': 'Quantum Rhythm Framework',
    'home.hero.title1': "The world doesn't need another diet.",
    'home.hero.title2': 'It needs rhythm.',
    'home.hero.subtitle': 'Discover the revolutionary approach to nutrition that restores biological and emotional alignment through rhythm, not restriction.',
    'home.hero.cta': 'Start Your 3-Month Rhythm Reset',
    'home.hero.tagline': 'Alignment not restriction. Because alignment restores vitality.',
    'home.why.title': 'Why Rhythm?',
    'home.why.p1': "Your body doesn't speak the language of calories or macros. It speaks the language of",
    'home.why.highlight': 'circadian rhythms',
    'home.why.p1end': ', seasonal cycles, and biological alignment.',
    'home.why.p2': 'The Quantum Rhythm Framework (QR) is the first nutritional methodology that treats time as a nutrient — restoring your body\'s natural intelligence through aligned eating patterns.',
    'home.phases.title': 'The Three Phases',
    'home.phases.decode.title': 'Decode',
    'home.phases.decode.desc': 'Understand your unique biological rhythm signature and identify misalignments causing fatigue, cravings, and inflammation.',
    'home.phases.reprogram.title': 'Reprogram',
    'home.phases.reprogram.desc': 'Reset your circadian clock through strategic meal timing, light exposure, and quantum-aligned nutrition protocols.',
    'home.phases.rebuild.title': 'Rebuild',
    'home.phases.rebuild.desc': 'Establish sustainable rhythms that restore vitality, mental clarity, and emotional resilience for life.',
    'home.phases.cta': 'Learn More About The Method',
    'home.cta.title': 'Ready to Restore Your Rhythm?',
    'home.cta.subtitle': 'Begin your transformation with personalized rhythm resets, printable tools, and quantum-aligned nutrition guidance.',
    'home.cta.programs': 'Explore Programs',
    'home.cta.consult': 'Book a Consultation',

    // About
    'about.badge': 'About Paula',
    'about.title': 'Bridging Biology, Rhythm & Consciousness',
    'about.intro1': 'is a forward-thinking wellness company led by Paula Carolina Suescun, a nutritionist, holistic health coach, and creator of the',
    'about.intro2': 'method.',
    'about.story1': 'The method focuses on restoring biological alignment through circadian, lunar, seasonal, and digestive rhythms. Integrating physiology, chronobiology, microbiome science, Chinese Medicine, biodynamics, and esoteric principles, Solaris Nutri offers a unique multidimensional approach to nutrition that reconnects individuals with their natural cycles.',
    'about.story2': "Paula's mission is to empower people to regain clarity, energy, and metabolic balance by understanding their body as a rhythmic system influenced by natural forces. Her work bridges science and intuitive knowledge, guiding clients toward sustainable wellbeing and deeper coherence with the living world.",
    'about.approach': 'My Approach',
    'about.approach1': 'Alignment over restriction — rhythm intelligence as foundation',
    'about.approach2': 'Integration of chronobiology, quantum biology, and planetary rhythms',
    'about.approach3': 'Food as frequency and information, not just calories',
    'about.approach4': 'Compassionate guidance rooted in love, kindness, and respect for nature',
    'about.credentials': 'My Credentials',
    'about.cred1': 'Nutritionist-Dietitian (UNAL - National University of Colombia)',
    'about.cred2': 'Certified Holistic Health Coach (IIN - Institute for Integrative Nutrition)',
    'about.cred3': 'Basic and advanced levels of Pranic Healing',
    'about.cred4': 'Creator of Quantum Rhythm Nutrition framework',
    'about.values': 'Core Values',
    'about.value.rhythm': 'Rhythm',
    'about.value.rhythm.desc': 'Honouring circadian, lunar, seasonal, and digestive cycles.',
    'about.value.nature': 'Nature',
    'about.value.nature.desc': 'Trusting natural simplicity as the ultimate teacher.',
    'about.value.integration': 'Integration',
    'about.value.integration.desc': 'Merging modern science with ancestral, biodynamic, Ayurvedic, and esoteric knowledge.',
    'about.value.education': 'Education',
    'about.value.education.desc': 'Empowering people through understanding.',
    'about.value.simplicity': 'Simplicity',
    'about.value.simplicity.desc': 'Restoring balance by removing complexity.',
    'about.value.evolution': 'Conscious Evolution',
    'about.value.evolution.desc': 'Supporting physical, emotional, and energetic growth.',
    'about.value.integrity': 'Natural Integrity',
    'about.value.integrity.desc': 'Choosing minimally industrialised foods that sustain vitality and ecological balance.',

    // Method
    'method.badge': 'The Method',
    'method.title': 'The Quantum Rhythm Framework',
    'method.subtitle': "Instead of counting calories or cutting more foods, we help you rebuild your natural rhythm – so your body feels safe, grounded, and ready to change.",
    'method.decode': 'Decode',
    'method.decode.desc': 'See your current rhythm.',
    'method.decode.intro': 'We begin with compassion, not judgement. Before changing anything, we observe and understand where you are — your sleep, meals, stress, emotions, and the survival patterns your spleen and nervous system have been holding.',
    'method.decode.title': 'What We Explore Together:',
    'method.decode.1': 'Your current rhythms: sleep, stress, meals, and emotions',
    'method.decode.2': 'How your spleen and nervous system are living in survival mode',
    'method.decode.3': 'Naming your patterns with love, not shame',
    'method.decode.4': 'Understanding your body\'s signals as wisdom, not weakness',
    'method.reprogram': 'Reprogram',
    'method.reprogram.desc': 'Calm and retune your system.',
    'method.reprogram.intro': 'Like retuning an instrument, we gently guide your nervous system and spleen from survival mode into safety. Small, rhythmic rituals replace stress-driven habits — and your body begins to soften.',
    'method.reprogram.title': 'How We Retune:',
    'method.reprogram.1': 'Gently reprogram survival patterns into safety signals',
    'method.reprogram.2': 'Introduce small, rhythmic rituals: regular warm meals, breath, light, sleep',
    'method.reprogram.3': 'Change how you eat before touching big food restrictions',
    'method.reprogram.4': 'First we calm your system, then food begins to change by itself',
    'method.rebuild': 'Rebuild',
    'method.rebuild.desc': 'Grow a new way of eating.',
    'method.rebuild.intro': 'We are not fixing what was broken — we are building the home your body always needed. New food habits grow naturally from consciousness, care, and love.',
    'method.rebuild.title': 'What Grows From Here:',
    'method.rebuild.1': 'A daily life built around a kind, stable rhythm',
    'method.rebuild.2': 'Food habits that grow from consciousness and care',
    'method.rebuild.3': 'A long-term relationship with food that feels natural and sustainable',
    'method.rebuild.4': 'A body that feels safe, grounded, and ready to evolve',
    'method.science': 'Scientific Foundation',
    'method.science.desc': 'The Quantum Rhythm Framework is grounded in peer-reviewed research on circadian biology, chrononutrition, and metabolic health.',
    'method.cta.title': 'Ready to Begin Your Rhythm Reset?',
    'method.cta.desc': 'Choose from 3-week, 6-week, or 9-week programs — each designed to guide you through all three phases.',
    'method.cta.button': 'Explore Programs',

    // Resources
    'resources.badge': 'Resources & Learning',
    'resources.title': 'Rhythm Tools & Guides',
    'resources.subtitle': 'Free downloads and masterclasses to support your journey back to natural alignment.',
    'resources.rhythmCalc': 'Rhythm Calculator',
    'resources.rhythmCalc.desc': 'Interactive assessment to discover your optimal eating windows.',
    'resources.rhythmPlanner': 'Rhythm Planner',
    'resources.rhythmPlanner.desc': 'Track your daily rhythms, energy patterns, and alignment progress.',
    'resources.cerealChart': 'Cereal of the Week Chart',
    'resources.cerealChart.desc': "Steiner's planetary grain wisdom for weekly rhythm integration.",
    'resources.springGuide': 'Spring Seasonal Guide',
    'resources.springGuide.desc': "Nourishment protocols aligned with spring's awakening energy.",
    'resources.summerGuide': 'Summer Seasonal Guide',
    'resources.summerGuide.desc': "Peak vitality nourishment for summer's expansive rhythms.",
    'resources.autumnGuide': 'Autumn Seasonal Guide',
    'resources.autumnGuide.desc': 'Grounding nutrition as nature turns inward.',
    'resources.winterGuide': 'Winter Seasonal Guide',
    'resources.winterGuide.desc': "Deep nourishment protocols for winter's restorative phase.",
    'resources.newsletter.title': 'Join the Rhythm Field',
    'resources.newsletter.desc': 'Receive planetary rhythm insights, seasonal nourishment guides, and exclusive access to new resources delivered to your inbox.',
    'resources.newsletter.placeholder': 'Enter your email',
    'resources.newsletter.button': 'Subscribe',
    'resources.startAssessment': 'Start Assessment',
    'resources.downloadFree': 'Download Free',
    'resources.interactiveTool': 'Interactive Tool',
    'resources.pdfDownload': 'PDF Download',

    // Blog
    'blog.badge': 'Journal',
    'blog.title': 'Rhythmic Reflections',
    'blog.subtitle': 'Insights on rhythm, planetary cycles, and the path back to natural alignment.',
    'blog.readMore': 'Read Full Article',
    'blog.newsletter.title': 'Never Miss a Reflection',
    'blog.newsletter.desc': 'Subscribe to receive new articles and rhythmic insights in your inbox.',

    // Shop
    'shop.badge': 'Artisan Nourishment',
    'shop.title': 'Solaris Granola',
    'shop.subtitle': "Handcrafted, rhythm-aligned granola slow-roasted at 120°C to preserve life force and nourish your body's natural intelligence.",
    'shop.product': 'Solaris Morning Granola',
    'shop.product.desc': 'A carefully curated blend of organic oats, seeds, nuts, and natural sweeteners, slow-roasted at precisely 120°C to maintain nutritional integrity and support your morning rhythm activation.',
    'shop.product.details': '350g · Handmade in small batches · Organic ingredients',
    'shop.orderNow': 'Order Now',
    'shop.whyTitle': 'Why Slow-Roasting at 120°C Matters',
    'shop.whyDesc': 'Temperature is everything. Unlike commercial granolas roasted at 180°C+, our gentle process honours the living intelligence within each ingredient.',
    'shop.feature1.title': 'Slow-Roasted at 120°C',
    'shop.feature1.desc': 'Low-temperature roasting preserves delicate nutrients, enzymes, and the natural life force of ingredients that high heat destroys.',
    'shop.feature2.title': 'Enzyme Preservation',
    'shop.feature2.desc': 'Cooking below 120°C maintains beneficial enzymes that aid digestion and nutrient absorption, keeping your gut rhythm aligned.',
    'shop.feature3.title': 'Enhanced Bioavailability',
    'shop.feature3.desc': 'Gentle roasting unlocks nutrients while maintaining their bioactive form, allowing your body to fully absorb and utilize them.',
    'shop.feature4.title': 'Rhythmic Nourishment',
    'shop.feature4.desc': 'Crafted to support your circadian rhythm — perfect for morning activation without the inflammatory stress of processed cereals.',
    'shop.science': 'The Science of Gentle Heat',
    'shop.science.p1': 'Above 120°C, many heat-sensitive nutrients begin to degrade. Vitamin C, B vitamins, and beneficial enzymes are particularly vulnerable to high temperatures.',
    'shop.science.p2': 'The Maillard reaction that creates that satisfying golden crunch can occur gently at lower temperatures, preserving flavour while protecting nutritional value.',
    'shop.science.p3': 'Slow roasting allows for even heat distribution, ensuring every oat, seed, and nut reaches its optimal state without the oxidative damage caused by rapid high-heat cooking.',

    // Retreat
    'retreat.badge': 'One-Day Realignment Retreat',
    'retreat.title': 'Earth Rhythm Reset',
    'retreat.subtitle': 'A structured, physiology-centered reset designed for small groups in a serene mud house surrounded by olive trees and the natural silence of the Algarve.',
    'retreat.location': 'Algarve, Portugal',
    'retreat.book': 'Book Your Retreat Experience',
    'retreat.whyTitle': 'Why This Retreat Works',
    'retreat.whyIntro': 'Your biology is rhythmic, electric, and adaptive. When stress, poor sleep, and modern life disrupt those rhythms, everything becomes harder: energy drops, digestion slows, inflammation rises, cravings intensify, and mental clarity fades.',
    'retreat.whyResult': 'The Earth Rhythm Reset restores coherence through a sequence of proven physiological levers:',
    'retreat.result': 'The result: your system finds flow again.',
    'retreat.schedule': 'The Experience',
    'retreat.takeHome': 'What You Take Home',
    'retreat.pricing': 'Pricing',
    'retreat.faq': 'Frequently Asked Questions',

    // Programs
    'programs.title': 'Transform Your Rhythm',
    'programs.subtitle': 'Choose your path to alignment. All programs include personalized support in English, Spanish, and Portuguese.',
    'programs.available': 'Available in English, Spanish & Portuguese',
    'programs.3month': '3-Month Rhythm Reset',
    'programs.6month': '6-Month Coherence Deepening',
    'programs.9month': '9-Month Full Quantum Rhythm Embodiment',
    'programs.book': 'Book Your Rhythm Consultation',
    'programs.popular': 'Most Popular',
    'programs.duration': 'Duration',
    'programs.investment': 'Investment',
    'programs.includes': 'What\'s Included',
    'programs.allInclude': 'All Programs Include',
    'programs.notSure': 'Not Sure Which Program?',
    'programs.notSure.desc': 'Book a free 20-minute discovery call to discuss your unique rhythm needs.',
    'programs.discovery': 'Schedule Discovery Call',
    
    // Contact
    'contact.badge': 'Contact',
    'contact.title': "Let's Begin Your Rhythm Journey",
    'contact.subtitle': 'Ready to begin your rhythm alignment journey? Consultations available in English, Spanish, and Portuguese.',
    'contact.languages': 'Consultations available in English, Spanish & Portuguese',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.interest': 'Interest',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.email.title': 'Email Directly',
    'contact.email.desc': 'For quick questions or inquiries',
    'contact.call.title': 'Book a Discovery Call',
    'contact.call.desc': 'Schedule a free 20-minute call to discuss your rhythm alignment needs',
    'contact.call.button': 'Schedule Call',
    'contact.expect': 'What to Expect',
    'contact.expect.1': 'Response within 24-48 hours',
    'contact.expect.2': 'Personalized guidance based on your needs',
    'contact.expect.3': 'No pressure, just information',
    'contact.quote': '"Every body has its own rhythm. My role is to help you rediscover yours."',
    
    // Calculator
    'calc.badge': 'Spleen Rhythm Assessment',
    'calc.title': 'Assess Your Digestive Rhythm',
    'calc.subtitle': 'Answer 10 questions to understand your spleen rhythm and receive personalized recommendations for the 3-Month Rhythm Reset Program.',
    'calc.instruction': 'Rate each statement 0–3:',
    'calc.never': 'Never',
    'calc.occasionally': 'Occasionally',
    'calc.frequently': 'Frequently',
    'calc.almostAlways': 'Almost Always',
    'calc.question': 'Question',
    'calc.of': 'of',
    'calc.select': 'Select the rating that best describes your experience',
    'calc.back': 'Back',
    'calc.next': 'Next',
    'calc.seeResults': 'See Results',
    'calc.results.title': 'Your Spleen Rhythm Assessment',
    'calc.results.score': 'Total Score',
    'calc.results.recommendations': 'Your Personalized Recommendations',
    'calc.results.nextSteps': 'Recommended Next Steps',
    'calc.results.retake': 'Retake Assessment',
    'calc.results.download': 'Download Your Results',
    'calc.results.ready': 'Ready to Restore Your Rhythm?',
    'calc.results.readyDesc': 'Discover how Quantum Rhythm Nutrition can help you realign with your body\'s natural intelligence.',
    'calc.results.bookConsult': 'Book Consultation',
    'calc.results.exploreResources': 'Explore Resources',
    'calc.results.viewPrograms': 'View Programs',
    'calc.results.exploreRetreat': 'Explore Earth Rhythm Reset Retreat',
    
    // Footer
    'footer.tagline': 'Guiding alignment across the seen and unseen bodies',
    'footer.rights': 'All rights reserved.',
    'footer.explore': 'Explore',
    'footer.connect': 'Connect',
    'footer.book': 'Book a Session',
    'footer.email': 'Email Us',
    'footer.createdBy': 'Created by Paula Carolina Suescun — BioRhythm Nutrition Coach & Nutritionist',
    
    // Common
    'common.learnMore': 'Learn More',
    'common.bookNow': 'Book Now',
    'common.comingSoon': 'Coming Soon',
    'common.enroll': 'Enroll Now',
    'common.register': 'Register Now',
    'common.free': 'Free',

    // Masterclass Section
    'masterclass.badge': 'Masterclasses',
    'masterclass.title': 'Deep Dive Learning',
    'masterclass.subtitle': 'Comprehensive masterclasses to deepen your understanding of rhythm, nourishment, and the hidden patterns that shape your vitality.',
    'masterclass.live': 'Live Masterclass',
    'masterclass.online': 'ONLINE MASTERCLASS',
    'masterclass.bundle': 'Complete Masterclass Bundle',
    'masterclass.bundleDesc': 'Access all masterclasses and save 30% with the complete bundle.',
    'masterclass.getBundle': 'Get Bundle Access',
    'masterclass.notify': 'Notify When Available',
  },
  es: {
    // Navigation
    'nav.about': 'Sobre Paula',
    'nav.method': 'El Método',
    'nav.programs': 'Programas',
    'nav.retreat': 'Retiro Ritmo Tierra',
    'nav.masterclass': 'Masterclass',
    'nav.resources': 'Recursos',
    'nav.tools': 'Herramientas',
    'nav.shop': 'Tienda',
    'nav.blog': 'Blog',
    'nav.contact': 'Contacto',
    'nav.foodRhythm': 'Herramienta de Ritmo',
    'nav.rhythmCalc': 'Calculadora de Ritmo',
    
    // Home
    'home.hero.badge': 'Marco de Ritmo Cuántico',
    'home.hero.title1': 'El mundo no necesita otra dieta.',
    'home.hero.title2': 'Necesita ritmo.',
    'home.hero.subtitle': 'Descubre el enfoque revolucionario de la nutrición que restaura la alineación biológica y emocional a través del ritmo, no la restricción.',
    'home.hero.cta': 'Comienza Tu Reset de Ritmo de 3 Meses',
    'home.hero.tagline': 'Alineación, no restricción. Porque la alineación restaura la vitalidad.',
    'home.why.title': '¿Por Qué Ritmo?',
    'home.why.p1': 'Tu cuerpo no habla el lenguaje de las calorías o los macros. Habla el lenguaje de los',
    'home.why.highlight': 'ritmos circadianos',
    'home.why.p1end': ', ciclos estacionales y alineación biológica.',
    'home.why.p2': 'El Marco de Ritmo Cuántico (QR) es la primera metodología nutricional que trata el tiempo como un nutriente — restaurando la inteligencia natural de tu cuerpo a través de patrones alimenticios alineados.',
    'home.phases.title': 'Las Tres Fases',
    'home.phases.decode.title': 'Decodificar',
    'home.phases.decode.desc': 'Comprende tu firma de ritmo biológico única e identifica las desalineaciones que causan fatiga, antojos e inflamación.',
    'home.phases.reprogram.title': 'Reprogramar',
    'home.phases.reprogram.desc': 'Restablece tu reloj circadiano a través de horarios estratégicos de comidas, exposición a la luz y protocolos de nutrición alineados.',
    'home.phases.rebuild.title': 'Reconstruir',
    'home.phases.rebuild.desc': 'Establece ritmos sostenibles que restauran la vitalidad, claridad mental y resiliencia emocional para toda la vida.',
    'home.phases.cta': 'Aprende Más Sobre El Método',
    'home.cta.title': '¿Lista para Restaurar Tu Ritmo?',
    'home.cta.subtitle': 'Comienza tu transformación con resets de ritmo personalizados, herramientas imprimibles y guía de nutrición alineada.',
    'home.cta.programs': 'Explorar Programas',
    'home.cta.consult': 'Reservar Consulta',

    // About
    'about.badge': 'Sobre Paula',
    'about.title': 'Conectando Biología, Ritmo y Consciencia',
    'about.intro1': 'es una empresa de bienestar vanguardista liderada por Paula Carolina Suescun, nutricionista, coach de salud holística y creadora del método',
    'about.intro2': '.',
    'about.story1': 'El método se enfoca en restaurar la alineación biológica a través de ritmos circadianos, lunares, estacionales y digestivos. Integrando fisiología, cronobiología, ciencia del microbioma, Medicina China, biodinámica y principios esotéricos, Solaris Nutri ofrece un enfoque multidimensional único de la nutrición que reconecta a las personas con sus ciclos naturales.',
    'about.story2': 'La misión de Paula es empoderar a las personas para recuperar claridad, energía y equilibrio metabólico al comprender su cuerpo como un sistema rítmico influenciado por fuerzas naturales. Su trabajo une ciencia y conocimiento intuitivo, guiando a los clientes hacia un bienestar sostenible y una coherencia más profunda con el mundo viviente.',
    'about.approach': 'Mi Enfoque',
    'about.approach1': 'Alineación sobre restricción — inteligencia rítmica como fundamento',
    'about.approach2': 'Integración de cronobiología, biología cuántica y ritmos planetarios',
    'about.approach3': 'Alimento como frecuencia e información, no solo calorías',
    'about.approach4': 'Guía compasiva enraizada en amor, amabilidad y respeto por la naturaleza',
    'about.credentials': 'Mis Credenciales',
    'about.cred1': 'Nutricionista-Dietista (UNAL - Universidad Nacional de Colombia)',
    'about.cred2': 'Coach de Salud Holística Certificada (IIN - Institute for Integrative Nutrition)',
    'about.cred3': 'Niveles básico y avanzado de Sanación Pránica',
    'about.cred4': 'Creadora del marco Quantum Rhythm Nutrition',
    'about.values': 'Valores Fundamentales',
    'about.value.rhythm': 'Ritmo',
    'about.value.rhythm.desc': 'Honrando los ciclos circadianos, lunares, estacionales y digestivos.',
    'about.value.nature': 'Naturaleza',
    'about.value.nature.desc': 'Confiando en la simplicidad natural como la maestra definitiva.',
    'about.value.integration': 'Integración',
    'about.value.integration.desc': 'Fusionando ciencia moderna con conocimiento ancestral, biodinámico, ayurvédico y esotérico.',
    'about.value.education': 'Educación',
    'about.value.education.desc': 'Empoderando a las personas a través de la comprensión.',
    'about.value.simplicity': 'Simplicidad',
    'about.value.simplicity.desc': 'Restaurando el equilibrio eliminando la complejidad.',
    'about.value.evolution': 'Evolución Consciente',
    'about.value.evolution.desc': 'Apoyando el crecimiento físico, emocional y energético.',
    'about.value.integrity': 'Integridad Natural',
    'about.value.integrity.desc': 'Eligiendo alimentos mínimamente industrializados que sostienen la vitalidad y el equilibrio ecológico.',

    // Method
    'method.badge': 'El Método',
    'method.title': 'El Marco de Ritmo Cuántico',
    'method.subtitle': 'En lugar de contar calorías o eliminar más alimentos, te ayudamos a reconstruir tu ritmo natural — para que tu cuerpo se sienta seguro, enraizado y listo para cambiar.',
    'method.decode': 'Decodificar',
    'method.decode.desc': 'Observa tu ritmo actual.',
    'method.decode.intro': 'Comenzamos con compasión, no con juicio. Antes de cambiar nada, observamos y entendemos dónde estás — tu sueño, comidas, estrés, emociones y los patrones de supervivencia que tu bazo y sistema nervioso han sostenido.',
    'method.decode.title': 'Lo Que Exploramos Juntos:',
    'method.decode.1': 'Tus ritmos actuales: sueño, estrés, comidas y emociones',
    'method.decode.2': 'Cómo tu bazo y sistema nervioso viven en modo supervivencia',
    'method.decode.3': 'Nombrar tus patrones con amor, no con vergüenza',
    'method.decode.4': 'Entender las señales de tu cuerpo como sabiduría, no como debilidad',
    'method.reprogram': 'Reprogramar',
    'method.reprogram.desc': 'Calma y resintoniza tu sistema.',
    'method.reprogram.intro': 'Como resintonizar un instrumento, guiamos suavemente tu sistema nervioso y bazo del modo supervivencia hacia la seguridad. Pequeños rituales rítmicos reemplazan los hábitos impulsados por el estrés — y tu cuerpo comienza a suavizarse.',
    'method.reprogram.title': 'Cómo Resintonizamos:',
    'method.reprogram.1': 'Reprogramar suavemente los patrones de supervivencia en señales de seguridad',
    'method.reprogram.2': 'Introducir pequeños rituales rítmicos: comidas cálidas regulares, respiración, luz, sueño',
    'method.reprogram.3': 'Cambiar cómo comes antes de tocar grandes restricciones alimentarias',
    'method.reprogram.4': 'Primero calmamos tu sistema, luego la comida comienza a cambiar sola',
    'method.rebuild': 'Reconstruir',
    'method.rebuild.desc': 'Cultiva una nueva forma de comer.',
    'method.rebuild.intro': 'No estamos arreglando lo que estaba roto — estamos construyendo el hogar que tu cuerpo siempre necesitó. Los nuevos hábitos alimentarios crecen naturalmente desde la consciencia, el cuidado y el amor.',
    'method.rebuild.title': 'Lo Que Crece Desde Aquí:',
    'method.rebuild.1': 'Una vida diaria construida alrededor de un ritmo amable y estable',
    'method.rebuild.2': 'Hábitos alimentarios que crecen desde la consciencia y el cuidado',
    'method.rebuild.3': 'Una relación a largo plazo con la comida que se siente natural y sostenible',
    'method.rebuild.4': 'Un cuerpo que se siente seguro, enraizado y listo para evolucionar',
    'method.science': 'Fundamento Científico',
    'method.science.desc': 'El Marco de Ritmo Cuántico está fundamentado en investigación revisada por pares sobre biología circadiana, crononutrición y salud metabólica.',
    'method.cta.title': '¿Lista para Comenzar Tu Reset de Ritmo?',
    'method.cta.desc': 'Elige entre programas de 3, 6 o 9 semanas — cada uno diseñado para guiarte a través de las tres fases.',
    'method.cta.button': 'Explorar Programas',

    // Resources
    'resources.badge': 'Recursos & Aprendizaje',
    'resources.title': 'Herramientas y Guías de Ritmo',
    'resources.subtitle': 'Descargas gratuitas y masterclasses para apoyar tu viaje de regreso a la alineación natural.',
    'resources.rhythmCalc': 'Calculadora de Ritmo',
    'resources.rhythmCalc.desc': 'Evaluación interactiva para descubrir tus ventanas óptimas de alimentación.',
    'resources.rhythmPlanner': 'Planificador de Ritmo',
    'resources.rhythmPlanner.desc': 'Rastrea tus ritmos diarios, patrones de energía y progreso de alineación.',
    'resources.cerealChart': 'Gráfico de Cereal de la Semana',
    'resources.cerealChart.desc': 'La sabiduría de los granos planetarios de Steiner para la integración del ritmo semanal.',
    'resources.springGuide': 'Guía Estacional de Primavera',
    'resources.springGuide.desc': 'Protocolos de nutrición alineados con la energía de despertar de la primavera.',
    'resources.summerGuide': 'Guía Estacional de Verano',
    'resources.summerGuide.desc': 'Nutrición de máxima vitalidad para los ritmos expansivos del verano.',
    'resources.autumnGuide': 'Guía Estacional de Otoño',
    'resources.autumnGuide.desc': 'Nutrición de arraigo mientras la naturaleza se vuelve hacia adentro.',
    'resources.winterGuide': 'Guía Estacional de Invierno',
    'resources.winterGuide.desc': 'Protocolos de nutrición profunda para la fase restauradora del invierno.',
    'resources.newsletter.title': 'Únete al Campo Rítmico',
    'resources.newsletter.desc': 'Recibe perspectivas de ritmos planetarios, guías de nutrición estacional y acceso exclusivo a nuevos recursos en tu bandeja de entrada.',
    'resources.newsletter.placeholder': 'Ingresa tu email',
    'resources.newsletter.button': 'Suscribirse',
    'resources.startAssessment': 'Iniciar Evaluación',
    'resources.downloadFree': 'Descargar Gratis',
    'resources.interactiveTool': 'Herramienta Interactiva',
    'resources.pdfDownload': 'Descarga PDF',

    // Blog
    'blog.badge': 'Diario',
    'blog.title': 'Reflexiones Rítmicas',
    'blog.subtitle': 'Perspectivas sobre ritmo, ciclos planetarios y el camino de regreso a la alineación natural.',
    'blog.readMore': 'Leer Artículo Completo',
    'blog.newsletter.title': 'Nunca Te Pierdas una Reflexión',
    'blog.newsletter.desc': 'Suscríbete para recibir nuevos artículos y perspectivas rítmicas en tu bandeja de entrada.',

    // Shop
    'shop.badge': 'Nutrición Artesanal',
    'shop.title': 'Granola Solaris',
    'shop.subtitle': 'Granola artesanal alineada con el ritmo, tostada lentamente a 120°C para preservar la fuerza vital y nutrir la inteligencia natural de tu cuerpo.',
    'shop.product': 'Granola Matutina Solaris',
    'shop.product.desc': 'Una mezcla cuidadosamente curada de avena orgánica, semillas, nueces y endulzantes naturales, tostada lentamente a precisamente 120°C para mantener la integridad nutricional y apoyar la activación de tu ritmo matutino.',
    'shop.product.details': '350g · Hecha a mano en pequeños lotes · Ingredientes orgánicos',
    'shop.orderNow': 'Ordenar Ahora',
    'shop.whyTitle': 'Por Qué Importa el Tostado Lento a 120°C',
    'shop.whyDesc': 'La temperatura es todo. A diferencia de las granolas comerciales tostadas a 180°C+, nuestro proceso suave honra la inteligencia viviente dentro de cada ingrediente.',
    'shop.feature1.title': 'Tostado Lento a 120°C',
    'shop.feature1.desc': 'El tostado a baja temperatura preserva nutrientes delicados, enzimas y la fuerza vital natural de los ingredientes que el calor alto destruye.',
    'shop.feature2.title': 'Preservación de Enzimas',
    'shop.feature2.desc': 'Cocinar por debajo de 120°C mantiene enzimas beneficiosas que ayudan a la digestión y absorción de nutrientes, manteniendo tu ritmo intestinal alineado.',
    'shop.feature3.title': 'Biodisponibilidad Mejorada',
    'shop.feature3.desc': 'El tostado suave desbloquea nutrientes mientras mantiene su forma bioactiva, permitiendo que tu cuerpo los absorba y utilice completamente.',
    'shop.feature4.title': 'Nutrición Rítmica',
    'shop.feature4.desc': 'Elaborada para apoyar tu ritmo circadiano — perfecta para la activación matutina sin el estrés inflamatorio de los cereales procesados.',
    'shop.science': 'La Ciencia del Calor Suave',
    'shop.science.p1': 'Por encima de 120°C, muchos nutrientes sensibles al calor comienzan a degradarse. La vitamina C, vitaminas B y enzimas beneficiosas son particularmente vulnerables a altas temperaturas.',
    'shop.science.p2': 'La reacción de Maillard que crea ese crujido dorado satisfactorio puede ocurrir suavemente a temperaturas más bajas, preservando el sabor mientras protege el valor nutricional.',
    'shop.science.p3': 'El tostado lento permite una distribución uniforme del calor, asegurando que cada avena, semilla y nuez alcance su estado óptimo sin el daño oxidativo causado por la cocción rápida a alto calor.',

    // Retreat
    'retreat.badge': 'Retiro de Realineación de Un Día',
    'retreat.title': 'Reset del Ritmo de la Tierra',
    'retreat.subtitle': 'Un reset estructurado centrado en la fisiología diseñado para grupos pequeños en una casa de barro serena rodeada de olivos y el silencio natural del Algarve.',
    'retreat.location': 'Algarve, Portugal',
    'retreat.book': 'Reserva Tu Experiencia de Retiro',
    'retreat.whyTitle': 'Por Qué Funciona Este Retiro',
    'retreat.whyIntro': 'Tu biología es rítmica, eléctrica y adaptativa. Cuando el estrés, el mal sueño y la vida moderna interrumpen esos ritmos, todo se vuelve más difícil: la energía baja, la digestión se ralentiza, la inflamación aumenta, los antojos se intensifican y la claridad mental se desvanece.',
    'retreat.whyResult': 'El Reset del Ritmo de la Tierra restaura la coherencia a través de una secuencia de palancas fisiológicas probadas:',
    'retreat.result': 'El resultado: tu sistema encuentra el flujo de nuevo.',
    'retreat.schedule': 'La Experiencia',
    'retreat.takeHome': 'Lo Que Te Llevas a Casa',
    'retreat.pricing': 'Precios',
    'retreat.faq': 'Preguntas Frecuentes',

    // Programs
    'programs.title': 'Transforma Tu Ritmo',
    'programs.subtitle': 'Elige tu camino hacia la alineación. Todos los programas incluyen apoyo personalizado en inglés, español y portugués.',
    'programs.available': 'Disponible en Inglés, Español y Portugués',
    'programs.3month': 'Reset de Ritmo de 3 Meses',
    'programs.6month': 'Profundización de Coherencia de 6 Meses',
    'programs.9month': 'Encarnación Completa de Ritmo Cuántico de 9 Meses',
    'programs.book': 'Reserva Tu Consulta de Ritmo',
    'programs.popular': 'Más Popular',
    'programs.duration': 'Duración',
    'programs.investment': 'Inversión',
    'programs.includes': 'Qué Incluye',
    'programs.allInclude': 'Todos los Programas Incluyen',
    'programs.notSure': '¿No Estás Segura de Cuál Programa?',
    'programs.notSure.desc': 'Reserva una llamada de descubrimiento gratuita de 20 minutos para discutir tus necesidades de ritmo únicas.',
    'programs.discovery': 'Agendar Llamada de Descubrimiento',
    
    // Contact
    'contact.badge': 'Contacto',
    'contact.title': 'Comencemos Tu Viaje Rítmico',
    'contact.subtitle': '¿Lista para comenzar tu viaje de alineación rítmica? Consultas disponibles en inglés, español y portugués.',
    'contact.languages': 'Consultas disponibles en Inglés, Español y Portugués',
    'contact.form.name': 'Nombre',
    'contact.form.email': 'Email',
    'contact.form.interest': 'Interés',
    'contact.form.message': 'Mensaje',
    'contact.form.send': 'Enviar Mensaje',
    'contact.email.title': 'Email Directo',
    'contact.email.desc': 'Para preguntas rápidas o consultas',
    'contact.call.title': 'Reservar Llamada de Descubrimiento',
    'contact.call.desc': 'Agenda una llamada gratuita de 20 minutos para discutir tus necesidades de alineación rítmica',
    'contact.call.button': 'Agendar Llamada',
    'contact.expect': 'Qué Esperar',
    'contact.expect.1': 'Respuesta en 24-48 horas',
    'contact.expect.2': 'Guía personalizada según tus necesidades',
    'contact.expect.3': 'Sin presión, solo información',
    'contact.quote': '"Cada cuerpo tiene su propio ritmo. Mi rol es ayudarte a redescubrir el tuyo."',
    
    // Calculator
    'calc.badge': 'Evaluación del Ritmo del Bazo',
    'calc.title': 'Evalúa Tu Ritmo Digestivo',
    'calc.subtitle': 'Responde 10 preguntas para comprender tu ritmo del bazo y recibe recomendaciones personalizadas para el Programa de Reset de Ritmo de 3 Meses.',
    'calc.instruction': 'Califica cada afirmación de 0 a 3:',
    'calc.never': 'Nunca',
    'calc.occasionally': 'Ocasionalmente',
    'calc.frequently': 'Frecuentemente',
    'calc.almostAlways': 'Casi Siempre',
    'calc.question': 'Pregunta',
    'calc.of': 'de',
    'calc.select': 'Selecciona la calificación que mejor describe tu experiencia',
    'calc.back': 'Atrás',
    'calc.next': 'Siguiente',
    'calc.seeResults': 'Ver Resultados',
    'calc.results.title': 'Tu Evaluación del Ritmo del Bazo',
    'calc.results.score': 'Puntuación Total',
    'calc.results.recommendations': 'Tus Recomendaciones Personalizadas',
    'calc.results.nextSteps': 'Próximos Pasos Recomendados',
    'calc.results.retake': 'Volver a Hacer la Evaluación',
    'calc.results.download': 'Descarga Tus Resultados',
    'calc.results.ready': '¿Lista para Restaurar Tu Ritmo?',
    'calc.results.readyDesc': 'Descubre cómo Quantum Rhythm Nutrition puede ayudarte a realinearte con la inteligencia natural de tu cuerpo.',
    'calc.results.bookConsult': 'Reservar Consulta',
    'calc.results.exploreResources': 'Explorar Recursos',
    'calc.results.viewPrograms': 'Ver Programas',
    'calc.results.exploreRetreat': 'Explorar Retiro Earth Rhythm Reset',
    
    // Footer
    'footer.tagline': 'Guiando la alineación a través de los cuerpos vistos e invisibles',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.explore': 'Explorar',
    'footer.connect': 'Conectar',
    'footer.book': 'Reservar Sesión',
    'footer.email': 'Envíanos un Email',
    'footer.createdBy': 'Creado por Paula Carolina Suescun — Coach de Nutrición BioRítmica y Nutricionista',
    
    // Common
    'common.learnMore': 'Saber Más',
    'common.bookNow': 'Reservar Ahora',
    'common.comingSoon': 'Próximamente',
    'common.enroll': 'Inscríbete Ahora',
    'common.register': 'Regístrate Ahora',
    'common.free': 'Gratis',

    // Masterclass Section
    'masterclass.badge': 'Masterclasses',
    'masterclass.title': 'Aprendizaje Profundo',
    'masterclass.subtitle': 'Masterclasses completas para profundizar tu comprensión del ritmo, la nutrición y los patrones ocultos que dan forma a tu vitalidad.',
    'masterclass.live': 'Masterclass en Vivo',
    'masterclass.online': 'MASTERCLASS ONLINE',
    'masterclass.bundle': 'Paquete Completo de Masterclasses',
    'masterclass.bundleDesc': 'Accede a todas las masterclasses y ahorra 30% con el paquete completo.',
    'masterclass.getBundle': 'Obtener Acceso al Paquete',
    'masterclass.notify': 'Notificar Cuando Esté Disponible',
  },
  pt: {
    // Navigation
    'nav.about': 'Sobre Paula',
    'nav.method': 'O Método',
    'nav.programs': 'Programas',
    'nav.retreat': 'Retiro Ritmo da Terra',
    'nav.resources': 'Recursos & Masterclass',
    'nav.tools': 'Ferramentas',
    'nav.shop': 'Loja',
    'nav.blog': 'Blog',
    'nav.contact': 'Contacto',
    'nav.foodRhythm': 'Ferramenta de Ritmo',
    'nav.rhythmCalc': 'Calculadora de Ritmo',
    
    // Home
    'home.hero.badge': 'Framework de Ritmo Quântico',
    'home.hero.title1': 'O mundo não precisa de outra dieta.',
    'home.hero.title2': 'Precisa de ritmo.',
    'home.hero.subtitle': 'Descubra a abordagem revolucionária da nutrição que restaura o alinhamento biológico e emocional através do ritmo, não da restrição.',
    'home.hero.cta': 'Comece Seu Reset de Ritmo de 3 Meses',
    'home.hero.tagline': 'Alinhamento, não restrição. Porque alinhamento restaura vitalidade.',
    'home.why.title': 'Por Que Ritmo?',
    'home.why.p1': 'Seu corpo não fala a linguagem de calorias ou macros. Fala a linguagem dos',
    'home.why.highlight': 'ritmos circadianos',
    'home.why.p1end': ', ciclos sazonais e alinhamento biológico.',
    'home.why.p2': 'O Framework de Ritmo Quântico (QR) é a primeira metodologia nutricional que trata o tempo como um nutriente — restaurando a inteligência natural do seu corpo através de padrões alimentares alinhados.',
    'home.phases.title': 'As Três Fases',
    'home.phases.decode.title': 'Decodificar',
    'home.phases.decode.desc': 'Entenda sua assinatura de ritmo biológico única e identifique os desalinhamentos que causam fadiga, desejos e inflamação.',
    'home.phases.reprogram.title': 'Reprogramar',
    'home.phases.reprogram.desc': 'Redefina seu relógio circadiano através de horários estratégicos de refeições, exposição à luz e protocolos de nutrição alinhados.',
    'home.phases.rebuild.title': 'Reconstruir',
    'home.phases.rebuild.desc': 'Estabeleça ritmos sustentáveis que restauram vitalidade, clareza mental e resiliência emocional para a vida.',
    'home.phases.cta': 'Saiba Mais Sobre O Método',
    'home.cta.title': 'Pronta para Restaurar Seu Ritmo?',
    'home.cta.subtitle': 'Comece sua transformação com resets de ritmo personalizados, ferramentas imprimíveis e orientação de nutrição alinhada.',
    'home.cta.programs': 'Explorar Programas',
    'home.cta.consult': 'Agendar Consulta',

    // About
    'about.badge': 'Sobre Paula',
    'about.title': 'Conectando Biologia, Ritmo e Consciência',
    'about.intro1': 'é uma empresa de bem-estar vanguardista liderada por Paula Carolina Suescun, nutricionista, coach de saúde holística e criadora do método',
    'about.intro2': '.',
    'about.story1': 'O método foca em restaurar o alinhamento biológico através de ritmos circadianos, lunares, sazonais e digestivos. Integrando fisiologia, cronobiologia, ciência do microbioma, Medicina Chinesa, biodinâmica e princípios esotéricos, Solaris Nutri oferece uma abordagem multidimensional única da nutrição que reconecta indivíduos com seus ciclos naturais.',
    'about.story2': 'A missão de Paula é capacitar as pessoas a recuperar clareza, energia e equilíbrio metabólico ao entender seu corpo como um sistema rítmico influenciado por forças naturais. Seu trabalho une ciência e conhecimento intuitivo, guiando clientes rumo ao bem-estar sustentável e uma coerência mais profunda com o mundo vivo.',
    'about.approach': 'Minha Abordagem',
    'about.approach1': 'Alinhamento sobre restrição — inteligência rítmica como fundamento',
    'about.approach2': 'Integração de cronobiologia, biologia quântica e ritmos planetários',
    'about.approach3': 'Alimento como frequência e informação, não apenas calorias',
    'about.approach4': 'Orientação compassiva enraizada em amor, bondade e respeito pela natureza',
    'about.credentials': 'Minhas Credenciais',
    'about.cred1': 'Nutricionista-Dietista (UNAL - Universidade Nacional da Colômbia)',
    'about.cred2': 'Coach de Saúde Holística Certificada (IIN - Institute for Integrative Nutrition)',
    'about.cred3': 'Níveis básico e avançado de Cura Prânica',
    'about.cred4': 'Criadora do framework Quantum Rhythm Nutrition',
    'about.values': 'Valores Fundamentais',
    'about.value.rhythm': 'Ritmo',
    'about.value.rhythm.desc': 'Honrando os ciclos circadianos, lunares, sazonais e digestivos.',
    'about.value.nature': 'Natureza',
    'about.value.nature.desc': 'Confiando na simplicidade natural como a mestra definitiva.',
    'about.value.integration': 'Integração',
    'about.value.integration.desc': 'Fundindo ciência moderna com conhecimento ancestral, biodinâmico, ayurvédico e esotérico.',
    'about.value.education': 'Educação',
    'about.value.education.desc': 'Capacitando as pessoas através da compreensão.',
    'about.value.simplicity': 'Simplicidade',
    'about.value.simplicity.desc': 'Restaurando o equilíbrio removendo a complexidade.',
    'about.value.evolution': 'Evolução Consciente',
    'about.value.evolution.desc': 'Apoiando o crescimento físico, emocional e energético.',
    'about.value.integrity': 'Integridade Natural',
    'about.value.integrity.desc': 'Escolhendo alimentos minimamente industrializados que sustentam vitalidade e equilíbrio ecológico.',

    // Method
    'method.badge': 'O Método',
    'method.title': 'O Framework de Ritmo Quântico',
    'method.subtitle': 'Em vez de contar calorias ou cortar mais alimentos, ajudamos você a reconstruir seu ritmo natural — para que seu corpo se sinta seguro, enraizado e pronto para mudar.',
    'method.decode': 'Decodificar',
    'method.decode.desc': 'Veja seu ritmo atual.',
    'method.decode.intro': 'Começamos com compaixão, não com julgamento. Antes de mudar qualquer coisa, observamos e entendemos onde você está — seu sono, refeições, estresse, emoções e os padrões de sobrevivência que seu baço e sistema nervoso têm sustentado.',
    'method.decode.title': 'O Que Exploramos Juntos:',
    'method.decode.1': 'Seus ritmos atuais: sono, estresse, refeições e emoções',
    'method.decode.2': 'Como seu baço e sistema nervoso vivem em modo de sobrevivência',
    'method.decode.3': 'Nomear seus padrões com amor, não com vergonha',
    'method.decode.4': 'Entender os sinais do seu corpo como sabedoria, não como fraqueza',
    'method.reprogram': 'Reprogramar',
    'method.reprogram.desc': 'Acalme e resintonize seu sistema.',
    'method.reprogram.intro': 'Como resintonizar um instrumento, guiamos suavemente seu sistema nervoso e baço do modo de sobrevivência para a segurança. Pequenos rituais rítmicos substituem hábitos movidos pelo estresse — e seu corpo começa a se suavizar.',
    'method.reprogram.title': 'Como Resintonizamos:',
    'method.reprogram.1': 'Reprogramar suavemente padrões de sobrevivência em sinais de segurança',
    'method.reprogram.2': 'Introduzir pequenos rituais rítmicos: refeições quentes regulares, respiração, luz, sono',
    'method.reprogram.3': 'Mudar como você come antes de tocar grandes restrições alimentares',
    'method.reprogram.4': 'Primeiro acalmamos seu sistema, depois a comida começa a mudar sozinha',
    'method.rebuild': 'Reconstruir',
    'method.rebuild.desc': 'Cultive uma nova forma de comer.',
    'method.rebuild.intro': 'Não estamos consertando o que estava quebrado — estamos construindo o lar que seu corpo sempre precisou. Novos hábitos alimentares crescem naturalmente da consciência, cuidado e amor.',
    'method.rebuild.title': 'O Que Cresce A Partir Daqui:',
    'method.rebuild.1': 'Uma vida diária construída ao redor de um ritmo gentil e estável',
    'method.rebuild.2': 'Hábitos alimentares que crescem da consciência e do cuidado',
    'method.rebuild.3': 'Uma relação de longo prazo com a comida que se sente natural e sustentável',
    'method.rebuild.4': 'Um corpo que se sente seguro, enraizado e pronto para evoluir',
    'method.science': 'Fundamento Científico',
    'method.science.desc': 'O Framework de Ritmo Quântico é fundamentado em pesquisa revisada por pares sobre biologia circadiana, crononutrição e saúde metabólica.',
    'method.cta.title': 'Pronta para Começar Seu Reset de Ritmo?',
    'method.cta.desc': 'Escolha entre programas de 3, 6 ou 9 semanas — cada um projetado para guiá-la através das três fases.',
    'method.cta.button': 'Explorar Programas',

    // Resources
    'resources.badge': 'Recursos & Aprendizado',
    'resources.title': 'Ferramentas e Guias de Ritmo',
    'resources.subtitle': 'Downloads gratuitos e masterclasses para apoiar sua jornada de volta ao alinhamento natural.',
    'resources.rhythmCalc': 'Calculadora de Ritmo',
    'resources.rhythmCalc.desc': 'Avaliação interativa para descobrir suas janelas ótimas de alimentação.',
    'resources.rhythmPlanner': 'Planejador de Ritmo',
    'resources.rhythmPlanner.desc': 'Acompanhe seus ritmos diários, padrões de energia e progresso de alinhamento.',
    'resources.cerealChart': 'Gráfico de Cereal da Semana',
    'resources.cerealChart.desc': 'A sabedoria dos grãos planetários de Steiner para integração do ritmo semanal.',
    'resources.springGuide': 'Guia Sazonal de Primavera',
    'resources.springGuide.desc': 'Protocolos de nutrição alinhados com a energia de despertar da primavera.',
    'resources.summerGuide': 'Guia Sazonal de Verão',
    'resources.summerGuide.desc': 'Nutrição de máxima vitalidade para os ritmos expansivos do verão.',
    'resources.autumnGuide': 'Guia Sazonal de Outono',
    'resources.autumnGuide.desc': 'Nutrição de enraizamento enquanto a natureza se volta para dentro.',
    'resources.winterGuide': 'Guia Sazonal de Inverno',
    'resources.winterGuide.desc': 'Protocolos de nutrição profunda para a fase restauradora do inverno.',
    'resources.newsletter.title': 'Junte-se ao Campo Rítmico',
    'resources.newsletter.desc': 'Receba insights de ritmos planetários, guias de nutrição sazonal e acesso exclusivo a novos recursos na sua caixa de entrada.',
    'resources.newsletter.placeholder': 'Digite seu email',
    'resources.newsletter.button': 'Inscrever-se',
    'resources.startAssessment': 'Iniciar Avaliação',
    'resources.downloadFree': 'Baixar Grátis',
    'resources.interactiveTool': 'Ferramenta Interativa',
    'resources.pdfDownload': 'Download PDF',

    // Blog
    'blog.badge': 'Diário',
    'blog.title': 'Reflexões Rítmicas',
    'blog.subtitle': 'Insights sobre ritmo, ciclos planetários e o caminho de volta ao alinhamento natural.',
    'blog.readMore': 'Ler Artigo Completo',
    'blog.newsletter.title': 'Nunca Perca uma Reflexão',
    'blog.newsletter.desc': 'Inscreva-se para receber novos artigos e insights rítmicos na sua caixa de entrada.',

    // Shop
    'shop.badge': 'Nutrição Artesanal',
    'shop.title': 'Granola Solaris',
    'shop.subtitle': 'Granola artesanal alinhada com o ritmo, torrada lentamente a 120°C para preservar a força vital e nutrir a inteligência natural do seu corpo.',
    'shop.product': 'Granola Matinal Solaris',
    'shop.product.desc': 'Uma mistura cuidadosamente curada de aveia orgânica, sementes, nozes e adoçantes naturais, torrada lentamente a precisamente 120°C para manter a integridade nutricional e apoiar a ativação do seu ritmo matinal.',
    'shop.product.details': '350g · Feita à mão em pequenos lotes · Ingredientes orgânicos',
    'shop.orderNow': 'Encomendar Agora',
    'shop.whyTitle': 'Por Que a Torra Lenta a 120°C Importa',
    'shop.whyDesc': 'A temperatura é tudo. Ao contrário das granolas comerciais torradas a 180°C+, nosso processo suave honra a inteligência viva dentro de cada ingrediente.',
    'shop.feature1.title': 'Torrada Lentamente a 120°C',
    'shop.feature1.desc': 'A torra em baixa temperatura preserva nutrientes delicados, enzimas e a força vital natural dos ingredientes que o calor alto destrói.',
    'shop.feature2.title': 'Preservação de Enzimas',
    'shop.feature2.desc': 'Cozinhar abaixo de 120°C mantém enzimas benéficas que auxiliam a digestão e absorção de nutrientes, mantendo seu ritmo intestinal alinhado.',
    'shop.feature3.title': 'Biodisponibilidade Melhorada',
    'shop.feature3.desc': 'A torra suave desbloqueia nutrientes enquanto mantém sua forma bioativa, permitindo que seu corpo os absorva e utilize completamente.',
    'shop.feature4.title': 'Nutrição Rítmica',
    'shop.feature4.desc': 'Elaborada para apoiar seu ritmo circadiano — perfeita para ativação matinal sem o estresse inflamatório dos cereais processados.',
    'shop.science': 'A Ciência do Calor Suave',
    'shop.science.p1': 'Acima de 120°C, muitos nutrientes sensíveis ao calor começam a degradar. A vitamina C, vitaminas B e enzimas benéficas são particularmente vulneráveis a altas temperaturas.',
    'shop.science.p2': 'A reação de Maillard que cria aquela crocância dourada satisfatória pode ocorrer suavemente em temperaturas mais baixas, preservando o sabor enquanto protege o valor nutricional.',
    'shop.science.p3': 'A torra lenta permite uma distribuição uniforme do calor, garantindo que cada aveia, semente e noz alcance seu estado ótimo sem o dano oxidativo causado pela cocção rápida em alto calor.',

    // Retreat
    'retreat.badge': 'Retiro de Realinhamento de Um Dia',
    'retreat.title': 'Reset do Ritmo da Terra',
    'retreat.subtitle': 'Um reset estruturado centrado na fisiologia projetado para pequenos grupos em uma casa de barro serena cercada por oliveiras e o silêncio natural do Algarve.',
    'retreat.location': 'Algarve, Portugal',
    'retreat.book': 'Reserve Sua Experiência de Retiro',
    'retreat.whyTitle': 'Por Que Este Retiro Funciona',
    'retreat.whyIntro': 'Sua biologia é rítmica, elétrica e adaptativa. Quando o estresse, o sono ruim e a vida moderna perturbam esses ritmos, tudo se torna mais difícil: a energia cai, a digestão desacelera, a inflamação aumenta, os desejos se intensificam e a clareza mental desvanece.',
    'retreat.whyResult': 'O Reset do Ritmo da Terra restaura a coerência através de uma sequência de alavancas fisiológicas comprovadas:',
    'retreat.result': 'O resultado: seu sistema encontra o fluxo novamente.',
    'retreat.schedule': 'A Experiência',
    'retreat.takeHome': 'O Que Você Leva para Casa',
    'retreat.pricing': 'Preços',
    'retreat.faq': 'Perguntas Frequentes',

    // Programs
    'programs.title': 'Transforme Seu Ritmo',
    'programs.subtitle': 'Escolha seu caminho para o alinhamento. Todos os programas incluem suporte personalizado em inglês, espanhol e português.',
    'programs.available': 'Disponível em Inglês, Espanhol e Português',
    'programs.3month': 'Reset de Ritmo de 3 Meses',
    'programs.6month': 'Aprofundamento de Coerência de 6 Meses',
    'programs.9month': 'Incorporação Completa de Ritmo Quântico de 9 Meses',
    'programs.book': 'Reserve Sua Consulta de Ritmo',
    'programs.popular': 'Mais Popular',
    'programs.duration': 'Duração',
    'programs.investment': 'Investimento',
    'programs.includes': 'O Que Inclui',
    'programs.allInclude': 'Todos os Programas Incluem',
    'programs.notSure': 'Não Tem Certeza de Qual Programa?',
    'programs.notSure.desc': 'Agende uma chamada de descoberta gratuita de 20 minutos para discutir suas necessidades de ritmo únicas.',
    'programs.discovery': 'Agendar Chamada de Descoberta',
    
    // Contact
    'contact.badge': 'Contacto',
    'contact.title': 'Vamos Começar Sua Jornada Rítmica',
    'contact.subtitle': 'Pronta para começar sua jornada de alinhamento rítmico? Consultas disponíveis em inglês, espanhol e português.',
    'contact.languages': 'Consultas disponíveis em Inglês, Espanhol e Português',
    'contact.form.name': 'Nome',
    'contact.form.email': 'Email',
    'contact.form.interest': 'Interesse',
    'contact.form.message': 'Mensagem',
    'contact.form.send': 'Enviar Mensagem',
    'contact.email.title': 'Email Direto',
    'contact.email.desc': 'Para perguntas rápidas ou consultas',
    'contact.call.title': 'Agendar Chamada de Descoberta',
    'contact.call.desc': 'Agende uma chamada gratuita de 20 minutos para discutir suas necessidades de alinhamento rítmico',
    'contact.call.button': 'Agendar Chamada',
    'contact.expect': 'O Que Esperar',
    'contact.expect.1': 'Resposta em 24-48 horas',
    'contact.expect.2': 'Orientação personalizada com base nas suas necessidades',
    'contact.expect.3': 'Sem pressão, apenas informação',
    'contact.quote': '"Cada corpo tem seu próprio ritmo. Meu papel é ajudá-la a redescobrir o seu."',
    
    // Calculator
    'calc.badge': 'Avaliação do Ritmo do Baço',
    'calc.title': 'Avalie Seu Ritmo Digestivo',
    'calc.subtitle': 'Responda 10 perguntas para entender seu ritmo do baço e receba recomendações personalizadas para o Programa de Reset de Ritmo de 3 Meses.',
    'calc.instruction': 'Classifique cada afirmação de 0 a 3:',
    'calc.never': 'Nunca',
    'calc.occasionally': 'Ocasionalmente',
    'calc.frequently': 'Frequentemente',
    'calc.almostAlways': 'Quase Sempre',
    'calc.question': 'Pergunta',
    'calc.of': 'de',
    'calc.select': 'Selecione a classificação que melhor descreve sua experiência',
    'calc.back': 'Voltar',
    'calc.next': 'Próximo',
    'calc.seeResults': 'Ver Resultados',
    'calc.results.title': 'Sua Avaliação do Ritmo do Baço',
    'calc.results.score': 'Pontuação Total',
    'calc.results.recommendations': 'Suas Recomendações Personalizadas',
    'calc.results.nextSteps': 'Próximos Passos Recomendados',
    'calc.results.retake': 'Refazer Avaliação',
    'calc.results.download': 'Baixe Seus Resultados',
    'calc.results.ready': 'Pronta para Restaurar Seu Ritmo?',
    'calc.results.readyDesc': 'Descubra como Quantum Rhythm Nutrition pode ajudá-la a realinhar-se com a inteligência natural do seu corpo.',
    'calc.results.bookConsult': 'Agendar Consulta',
    'calc.results.exploreResources': 'Explorar Recursos',
    'calc.results.viewPrograms': 'Ver Programas',
    'calc.results.exploreRetreat': 'Explorar Retiro Earth Rhythm Reset',
    
    // Footer
    'footer.tagline': 'Guiando o alinhamento através dos corpos vistos e invistos',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.explore': 'Explorar',
    'footer.connect': 'Conectar',
    'footer.book': 'Agendar Sessão',
    'footer.email': 'Envie um Email',
    'footer.createdBy': 'Criado por Paula Carolina Suescun — Coach de Nutrição BioRítmica e Nutricionista',
    
    // Common
    'common.learnMore': 'Saiba Mais',
    'common.bookNow': 'Reserve Agora',
    'common.comingSoon': 'Em Breve',
    'common.enroll': 'Inscreva-se Agora',
    'common.register': 'Registre-se Agora',
    'common.free': 'Grátis',

    // Masterclass Section
    'masterclass.badge': 'Masterclasses',
    'masterclass.title': 'Aprendizado Profundo',
    'masterclass.subtitle': 'Masterclasses completas para aprofundar sua compreensão do ritmo, nutrição e os padrões ocultos que moldam sua vitalidade.',
    'masterclass.live': 'Masterclass ao Vivo',
    'masterclass.online': 'MASTERCLASS ONLINE',
    'masterclass.bundle': 'Pacote Completo de Masterclasses',
    'masterclass.bundleDesc': 'Acesse todas as masterclasses e economize 30% com o pacote completo.',
    'masterclass.getBundle': 'Obter Acesso ao Pacote',
    'masterclass.notify': 'Notificar Quando Disponível',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
